//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BF.SMS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SMS.wmgwSoap")]
    public interface wmgwSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 userId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MongateCsSpSendSmsNew", ReplyAction="*")]
        BF.SMS.MongateCsSpSendSmsNewResponse MongateCsSpSendSmsNew(BF.SMS.MongateCsSpSendSmsNewRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 userId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MongateSendSubmit", ReplyAction="*")]
        BF.SMS.MongateSendSubmitResponse MongateSendSubmit(BF.SMS.MongateSendSubmitRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 userId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MongateMULTIXSend", ReplyAction="*")]
        BF.SMS.MongateMULTIXSendResponse MongateMULTIXSend(BF.SMS.MongateMULTIXSendRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 userId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MongateCsGetSmsExEx", ReplyAction="*")]
        BF.SMS.MongateCsGetSmsExExResponse MongateCsGetSmsExEx(BF.SMS.MongateCsGetSmsExExRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 userId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MongateCsGetStatusReportExEx", ReplyAction="*")]
        BF.SMS.MongateCsGetStatusReportExExResponse MongateCsGetStatusReportExEx(BF.SMS.MongateCsGetStatusReportExExRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 userId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MongateQueryBalance", ReplyAction="*")]
        BF.SMS.MongateQueryBalanceResponse MongateQueryBalance(BF.SMS.MongateQueryBalanceRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 userId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MongateGetDeliver", ReplyAction="*")]
        BF.SMS.MongateGetDeliverResponse MongateGetDeliver(BF.SMS.MongateGetDeliverRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MongateCsSpSendSmsNewRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MongateCsSpSendSmsNew", Namespace="http://tempuri.org/", Order=0)]
        public BF.SMS.MongateCsSpSendSmsNewRequestBody Body;
        
        public MongateCsSpSendSmsNewRequest() {
        }
        
        public MongateCsSpSendSmsNewRequest(BF.SMS.MongateCsSpSendSmsNewRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MongateCsSpSendSmsNewRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pszMobis;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string pszMsg;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int iMobiCount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string pszSubPort;
        
        public MongateCsSpSendSmsNewRequestBody() {
        }
        
        public MongateCsSpSendSmsNewRequestBody(string userId, string password, string pszMobis, string pszMsg, int iMobiCount, string pszSubPort) {
            this.userId = userId;
            this.password = password;
            this.pszMobis = pszMobis;
            this.pszMsg = pszMsg;
            this.iMobiCount = iMobiCount;
            this.pszSubPort = pszSubPort;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MongateCsSpSendSmsNewResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MongateCsSpSendSmsNewResponse", Namespace="http://tempuri.org/", Order=0)]
        public BF.SMS.MongateCsSpSendSmsNewResponseBody Body;
        
        public MongateCsSpSendSmsNewResponse() {
        }
        
        public MongateCsSpSendSmsNewResponse(BF.SMS.MongateCsSpSendSmsNewResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MongateCsSpSendSmsNewResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MongateCsSpSendSmsNewResult;
        
        public MongateCsSpSendSmsNewResponseBody() {
        }
        
        public MongateCsSpSendSmsNewResponseBody(string MongateCsSpSendSmsNewResult) {
            this.MongateCsSpSendSmsNewResult = MongateCsSpSendSmsNewResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MongateSendSubmitRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MongateSendSubmit", Namespace="http://tempuri.org/", Order=0)]
        public BF.SMS.MongateSendSubmitRequestBody Body;
        
        public MongateSendSubmitRequest() {
        }
        
        public MongateSendSubmitRequest(BF.SMS.MongateSendSubmitRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MongateSendSubmitRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pszMobis;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string pszMsg;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int iMobiCount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string pszSubPort;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string MsgId;
        
        public MongateSendSubmitRequestBody() {
        }
        
        public MongateSendSubmitRequestBody(string userId, string password, string pszMobis, string pszMsg, int iMobiCount, string pszSubPort, string MsgId) {
            this.userId = userId;
            this.password = password;
            this.pszMobis = pszMobis;
            this.pszMsg = pszMsg;
            this.iMobiCount = iMobiCount;
            this.pszSubPort = pszSubPort;
            this.MsgId = MsgId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MongateSendSubmitResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MongateSendSubmitResponse", Namespace="http://tempuri.org/", Order=0)]
        public BF.SMS.MongateSendSubmitResponseBody Body;
        
        public MongateSendSubmitResponse() {
        }
        
        public MongateSendSubmitResponse(BF.SMS.MongateSendSubmitResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MongateSendSubmitResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MongateSendSubmitResult;
        
        public MongateSendSubmitResponseBody() {
        }
        
        public MongateSendSubmitResponseBody(string MongateSendSubmitResult) {
            this.MongateSendSubmitResult = MongateSendSubmitResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MongateMULTIXSendRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MongateMULTIXSend", Namespace="http://tempuri.org/", Order=0)]
        public BF.SMS.MongateMULTIXSendRequestBody Body;
        
        public MongateMULTIXSendRequest() {
        }
        
        public MongateMULTIXSendRequest(BF.SMS.MongateMULTIXSendRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MongateMULTIXSendRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string multixmt;
        
        public MongateMULTIXSendRequestBody() {
        }
        
        public MongateMULTIXSendRequestBody(string userId, string password, string multixmt) {
            this.userId = userId;
            this.password = password;
            this.multixmt = multixmt;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MongateMULTIXSendResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MongateMULTIXSendResponse", Namespace="http://tempuri.org/", Order=0)]
        public BF.SMS.MongateMULTIXSendResponseBody Body;
        
        public MongateMULTIXSendResponse() {
        }
        
        public MongateMULTIXSendResponse(BF.SMS.MongateMULTIXSendResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MongateMULTIXSendResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MongateMULTIXSendResult;
        
        public MongateMULTIXSendResponseBody() {
        }
        
        public MongateMULTIXSendResponseBody(string MongateMULTIXSendResult) {
            this.MongateMULTIXSendResult = MongateMULTIXSendResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MongateCsGetSmsExExRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MongateCsGetSmsExEx", Namespace="http://tempuri.org/", Order=0)]
        public BF.SMS.MongateCsGetSmsExExRequestBody Body;
        
        public MongateCsGetSmsExExRequest() {
        }
        
        public MongateCsGetSmsExExRequest(BF.SMS.MongateCsGetSmsExExRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MongateCsGetSmsExExRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public MongateCsGetSmsExExRequestBody() {
        }
        
        public MongateCsGetSmsExExRequestBody(string userId, string password) {
            this.userId = userId;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MongateCsGetSmsExExResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MongateCsGetSmsExExResponse", Namespace="http://tempuri.org/", Order=0)]
        public BF.SMS.MongateCsGetSmsExExResponseBody Body;
        
        public MongateCsGetSmsExExResponse() {
        }
        
        public MongateCsGetSmsExExResponse(BF.SMS.MongateCsGetSmsExExResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MongateCsGetSmsExExResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BF.SMS.ArrayOfString MongateCsGetSmsExExResult;
        
        public MongateCsGetSmsExExResponseBody() {
        }
        
        public MongateCsGetSmsExExResponseBody(BF.SMS.ArrayOfString MongateCsGetSmsExExResult) {
            this.MongateCsGetSmsExExResult = MongateCsGetSmsExExResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MongateCsGetStatusReportExExRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MongateCsGetStatusReportExEx", Namespace="http://tempuri.org/", Order=0)]
        public BF.SMS.MongateCsGetStatusReportExExRequestBody Body;
        
        public MongateCsGetStatusReportExExRequest() {
        }
        
        public MongateCsGetStatusReportExExRequest(BF.SMS.MongateCsGetStatusReportExExRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MongateCsGetStatusReportExExRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public MongateCsGetStatusReportExExRequestBody() {
        }
        
        public MongateCsGetStatusReportExExRequestBody(string userId, string password) {
            this.userId = userId;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MongateCsGetStatusReportExExResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MongateCsGetStatusReportExExResponse", Namespace="http://tempuri.org/", Order=0)]
        public BF.SMS.MongateCsGetStatusReportExExResponseBody Body;
        
        public MongateCsGetStatusReportExExResponse() {
        }
        
        public MongateCsGetStatusReportExExResponse(BF.SMS.MongateCsGetStatusReportExExResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MongateCsGetStatusReportExExResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BF.SMS.ArrayOfString MongateCsGetStatusReportExExResult;
        
        public MongateCsGetStatusReportExExResponseBody() {
        }
        
        public MongateCsGetStatusReportExExResponseBody(BF.SMS.ArrayOfString MongateCsGetStatusReportExExResult) {
            this.MongateCsGetStatusReportExExResult = MongateCsGetStatusReportExExResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MongateQueryBalanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MongateQueryBalance", Namespace="http://tempuri.org/", Order=0)]
        public BF.SMS.MongateQueryBalanceRequestBody Body;
        
        public MongateQueryBalanceRequest() {
        }
        
        public MongateQueryBalanceRequest(BF.SMS.MongateQueryBalanceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MongateQueryBalanceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public MongateQueryBalanceRequestBody() {
        }
        
        public MongateQueryBalanceRequestBody(string userId, string password) {
            this.userId = userId;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MongateQueryBalanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MongateQueryBalanceResponse", Namespace="http://tempuri.org/", Order=0)]
        public BF.SMS.MongateQueryBalanceResponseBody Body;
        
        public MongateQueryBalanceResponse() {
        }
        
        public MongateQueryBalanceResponse(BF.SMS.MongateQueryBalanceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MongateQueryBalanceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int MongateQueryBalanceResult;
        
        public MongateQueryBalanceResponseBody() {
        }
        
        public MongateQueryBalanceResponseBody(int MongateQueryBalanceResult) {
            this.MongateQueryBalanceResult = MongateQueryBalanceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MongateGetDeliverRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MongateGetDeliver", Namespace="http://tempuri.org/", Order=0)]
        public BF.SMS.MongateGetDeliverRequestBody Body;
        
        public MongateGetDeliverRequest() {
        }
        
        public MongateGetDeliverRequest(BF.SMS.MongateGetDeliverRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MongateGetDeliverRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int iReqType;
        
        public MongateGetDeliverRequestBody() {
        }
        
        public MongateGetDeliverRequestBody(string userId, string password, int iReqType) {
            this.userId = userId;
            this.password = password;
            this.iReqType = iReqType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MongateGetDeliverResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MongateGetDeliverResponse", Namespace="http://tempuri.org/", Order=0)]
        public BF.SMS.MongateGetDeliverResponseBody Body;
        
        public MongateGetDeliverResponse() {
        }
        
        public MongateGetDeliverResponse(BF.SMS.MongateGetDeliverResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MongateGetDeliverResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BF.SMS.ArrayOfString MongateGetDeliverResult;
        
        public MongateGetDeliverResponseBody() {
        }
        
        public MongateGetDeliverResponseBody(BF.SMS.ArrayOfString MongateGetDeliverResult) {
            this.MongateGetDeliverResult = MongateGetDeliverResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wmgwSoapChannel : BF.SMS.wmgwSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wmgwSoapClient : System.ServiceModel.ClientBase<BF.SMS.wmgwSoap>, BF.SMS.wmgwSoap {
        
        public wmgwSoapClient() {
        }
        
        public wmgwSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wmgwSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wmgwSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wmgwSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BF.SMS.MongateCsSpSendSmsNewResponse BF.SMS.wmgwSoap.MongateCsSpSendSmsNew(BF.SMS.MongateCsSpSendSmsNewRequest request) {
            return base.Channel.MongateCsSpSendSmsNew(request);
        }
        
        public string MongateCsSpSendSmsNew(string userId, string password, string pszMobis, string pszMsg, int iMobiCount, string pszSubPort) {
            BF.SMS.MongateCsSpSendSmsNewRequest inValue = new BF.SMS.MongateCsSpSendSmsNewRequest();
            inValue.Body = new BF.SMS.MongateCsSpSendSmsNewRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.password = password;
            inValue.Body.pszMobis = pszMobis;
            inValue.Body.pszMsg = pszMsg;
            inValue.Body.iMobiCount = iMobiCount;
            inValue.Body.pszSubPort = pszSubPort;
            BF.SMS.MongateCsSpSendSmsNewResponse retVal = ((BF.SMS.wmgwSoap)(this)).MongateCsSpSendSmsNew(inValue);
            return retVal.Body.MongateCsSpSendSmsNewResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BF.SMS.MongateSendSubmitResponse BF.SMS.wmgwSoap.MongateSendSubmit(BF.SMS.MongateSendSubmitRequest request) {
            return base.Channel.MongateSendSubmit(request);
        }
        
        public string MongateSendSubmit(string userId, string password, string pszMobis, string pszMsg, int iMobiCount, string pszSubPort, string MsgId) {
            BF.SMS.MongateSendSubmitRequest inValue = new BF.SMS.MongateSendSubmitRequest();
            inValue.Body = new BF.SMS.MongateSendSubmitRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.password = password;
            inValue.Body.pszMobis = pszMobis;
            inValue.Body.pszMsg = pszMsg;
            inValue.Body.iMobiCount = iMobiCount;
            inValue.Body.pszSubPort = pszSubPort;
            inValue.Body.MsgId = MsgId;
            BF.SMS.MongateSendSubmitResponse retVal = ((BF.SMS.wmgwSoap)(this)).MongateSendSubmit(inValue);
            return retVal.Body.MongateSendSubmitResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BF.SMS.MongateMULTIXSendResponse BF.SMS.wmgwSoap.MongateMULTIXSend(BF.SMS.MongateMULTIXSendRequest request) {
            return base.Channel.MongateMULTIXSend(request);
        }
        
        public string MongateMULTIXSend(string userId, string password, string multixmt) {
            BF.SMS.MongateMULTIXSendRequest inValue = new BF.SMS.MongateMULTIXSendRequest();
            inValue.Body = new BF.SMS.MongateMULTIXSendRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.password = password;
            inValue.Body.multixmt = multixmt;
            BF.SMS.MongateMULTIXSendResponse retVal = ((BF.SMS.wmgwSoap)(this)).MongateMULTIXSend(inValue);
            return retVal.Body.MongateMULTIXSendResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BF.SMS.MongateCsGetSmsExExResponse BF.SMS.wmgwSoap.MongateCsGetSmsExEx(BF.SMS.MongateCsGetSmsExExRequest request) {
            return base.Channel.MongateCsGetSmsExEx(request);
        }
        
        public BF.SMS.ArrayOfString MongateCsGetSmsExEx(string userId, string password) {
            BF.SMS.MongateCsGetSmsExExRequest inValue = new BF.SMS.MongateCsGetSmsExExRequest();
            inValue.Body = new BF.SMS.MongateCsGetSmsExExRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.password = password;
            BF.SMS.MongateCsGetSmsExExResponse retVal = ((BF.SMS.wmgwSoap)(this)).MongateCsGetSmsExEx(inValue);
            return retVal.Body.MongateCsGetSmsExExResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BF.SMS.MongateCsGetStatusReportExExResponse BF.SMS.wmgwSoap.MongateCsGetStatusReportExEx(BF.SMS.MongateCsGetStatusReportExExRequest request) {
            return base.Channel.MongateCsGetStatusReportExEx(request);
        }
        
        public BF.SMS.ArrayOfString MongateCsGetStatusReportExEx(string userId, string password) {
            BF.SMS.MongateCsGetStatusReportExExRequest inValue = new BF.SMS.MongateCsGetStatusReportExExRequest();
            inValue.Body = new BF.SMS.MongateCsGetStatusReportExExRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.password = password;
            BF.SMS.MongateCsGetStatusReportExExResponse retVal = ((BF.SMS.wmgwSoap)(this)).MongateCsGetStatusReportExEx(inValue);
            return retVal.Body.MongateCsGetStatusReportExExResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BF.SMS.MongateQueryBalanceResponse BF.SMS.wmgwSoap.MongateQueryBalance(BF.SMS.MongateQueryBalanceRequest request) {
            return base.Channel.MongateQueryBalance(request);
        }
        
        public int MongateQueryBalance(string userId, string password) {
            BF.SMS.MongateQueryBalanceRequest inValue = new BF.SMS.MongateQueryBalanceRequest();
            inValue.Body = new BF.SMS.MongateQueryBalanceRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.password = password;
            BF.SMS.MongateQueryBalanceResponse retVal = ((BF.SMS.wmgwSoap)(this)).MongateQueryBalance(inValue);
            return retVal.Body.MongateQueryBalanceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BF.SMS.MongateGetDeliverResponse BF.SMS.wmgwSoap.MongateGetDeliver(BF.SMS.MongateGetDeliverRequest request) {
            return base.Channel.MongateGetDeliver(request);
        }
        
        public BF.SMS.ArrayOfString MongateGetDeliver(string userId, string password, int iReqType) {
            BF.SMS.MongateGetDeliverRequest inValue = new BF.SMS.MongateGetDeliverRequest();
            inValue.Body = new BF.SMS.MongateGetDeliverRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.password = password;
            inValue.Body.iReqType = iReqType;
            BF.SMS.MongateGetDeliverResponse retVal = ((BF.SMS.wmgwSoap)(this)).MongateGetDeliver(inValue);
            return retVal.Body.MongateGetDeliverResult;
        }
    }
}
