var logoMenu = [
   { id: 1, pId: 0, name: "CRMWEB平台", title: "1" },
   { id: 11, pId: 1, name: "会员卡", title: "1" },
       { id: 110, pId: 11, name: "CRM管理", title: "1" },
     { id: 1101, pId: 110, name: "商户定义", title: "ys", value: "CrmWeb/CRMGL/SHDY/CRMGL_SHDY.aspx" },
     { id: 1101, pId: 110, name: "管辖商户定义", title: "ys", value: "CrmWeb/CRMGL/GXSHDY/CRMGL_GXSHDY.aspx" },
     { id: 1102, pId: 110, name: "门店定义", title: "ys", value: "CrmWeb/CRMGL/MDDY/CRMGL_MDDY.aspx" },
     { id: 1103, pId: 110, name: "管辖数据定义", title: "ys", value: "CrmWeb/CRMGL/GXSJDY/CRMGL_GXSJDY_Srch.aspx" },
     { id: 1163, pId: 110, name: "会员区域定义", title: "zs", value: "CrmWeb/CRMGL/HYQYDY/CRMGL_HYQYDY.aspx" },
     { id: 1163, pId: 110, name: "商圈类型定义", title: "zs", value: "CrmWeb/CRMGL/SQLXDY/CRMGL_SQLXDY_Srch.aspx" },
     { id: 1163, pId: 110, name: "商圈定义", title: "zs", value: "CrmWeb/CRMGL/SQDY/CRMGL_SQDY_Srch.aspx" },
     { id: 1164, pId: 110, name: "发行单位定义", title: "zs", value: "CrmWeb/CRMGL/FXDWDY/CRMGL_FXDWDY.aspx" },
     { id: 1166, pId: 110, name: "银行信息定义", title: "ys", value: "CrmWeb/CRMGL/YHXXDY/CRMGL_YHXXDY.aspx" },
     { id: 1165, pId: 110, name: "时段定义", title: "zs", value: "CrmWeb/CRMGL/SDDY/CRMGL_SDDY.aspx" },
     { id: 1165, pId: 110, name: "年龄段定义", title: "zs", value: "CrmWeb/CRMGL/NLDDY/CRMGL_NLDDY.aspx" },
     { id: 1166, pId: 110, name: "优惠券定义", title: "zs", value: "CrmWeb/CRMGL/YHQDY/CRMGL_YHQDY_Srch.aspx" },
     { id: 1166, pId: 110, name: "促销优惠券定义", title: "zs", value: "CrmWeb/CRMGL/CXYHQDY/CRMGL_CXYHQDY_Srch.aspx" },
     { id: 1166, pId: 110, name: "优惠券使用商户定义", title: "zs", value: "CrmWeb/CRMGL/YHQSYSH/CRMGL_YHQSYSH_Srch.aspx" },
     { id: 1166, pId: 110, name: "商户支付方式定义", title: "zs", value: "CrmWeb/CRMGL/SHZFFSDEF/CRMGL_SHZFFSDEF.aspx" },
     { id: 1104, pId: 110, name: "商户支付方式门店积分比例", title: "ys", value: "CrmWeb/CRMGL/SHZFFSMDJFBL/CRMGL_SHZFFSMDJFBL_Srch.aspx" },
     { id: 1166, pId: 110, name: "卡系统支付方式定义", title: "zs", value: "CrmWeb/CRMGL/ZFFSDY/CRMGL_ZFFSDY.aspx" },
     { id: 1166, pId: 110, name: "会员卡卡种定义", title: "ys", value: "CrmWeb/CRMGL/KZDY/CRMGL_KZDY_Srch.aspx?czk=0" },
     { id: 1166, pId: 110, name: "会员卡类型定义", title: "ys", value: "CrmWeb/CRMGL/KLXDY/CRMGL_KLXDY_Srch.aspx?czk=0" },
     { id: 1166, pId: 110, name: "CRM操作员权限定义", title: "ys", value: "CrmWeb/CRMGL/CRMCZQX/CRMGL_CRMCZQX.aspx?czy=1&personid=10002" },
     { id: 1166, pId: 110, name: "CRM操作员组权限定义", title: "ys", value: "CrmWeb/CRMGL/CRMCZQX/CRMGL_CRMCZQX.aspx?czy=0&personid=1" },
     { id: 1166, pId: 110, name: "CRM系统参数定义", title: "ys", value: "CrmWeb/CRMGL/XTCSDY/CRMGL_XTCSDY.aspx" },
     { id: 1166, pId: 110, name: "门店数据库定义", title: "ys", value: "CrmWeb/CRMGL/JXCDB/CRMGL_JXCDB.aspx" },
     { id: 1166, pId: 110, name: "系统数据平衡性检查", title: "ys", value: "CrmWeb/CRMGL/XTSJPHJC/CRMGL_XTSJPHJC_Srch.aspx" },
     { id: 1166, pId: 110, name: "面值卡卡种定义", title: "zs", value: "CrmWeb/CRMGL/KZDY/CRMGL_KZDY_Srch.aspx?czk=1" },
     { id: 1166, pId: 110, name: "面值卡类型定义", title: "zs", value: "CrmWeb/CRMGL/KLXDY/CRMGL_KLXDY_Srch.aspx?czk=1" },
     { id: 1104, pId: 110, name: "发行渠道定义", title: "ys", value: "CrmWeb/CRMGL/FXQDDY/CRMGL_FXQDDY.aspx" },
     { id: 1104, pId: 110, name: "小区定义", title: "ys", value: "CrmWeb/CRMGL/LQXQDY/CRMGL_LQXQDY_Srch.aspx" },
     { id: 1104, pId: 110, name: "小区商圈定义", title: "ys", value: "CrmWeb/CRMGL/XQSQDY/CRMGL_XQSQDY.aspx" },
     { id: 1104, pId: 110, name: "前台卡管理员", title: "ys", value: "CrmWeb/CRMGL/QTKGLYDEF/CRMGL_QTKGLYDEF.aspx" },
     { id: 1104, pId: 110, name: "移动POS信息", title: "ys", value: "CrmWeb/CRMGL/YHPOSXX/CRMGL_YHPOSXX.aspx" },
     { id: 1104, pId: 110, name: "职业定义", title: "ys", value: "CrmWeb/CRMGL/ZYDY/CRMGL_ZYDY.aspx" },
     { id: 1163, pId: 110, name: "商品价格带定义", title: "zs", value: "CrmWeb/CRMGL/SPJGDDY/CRMGL_SPJGDDY.aspx" },
     { id: 1163, pId: 110, name: "商户优惠券支付方式定义", title: "zs", value: "CrmWeb/CRMGL/SHYHQZFFSDY/CRMGL_SHYHQZFFSDY.aspx" },
     { id: 1163, pId: 110, name: "短信发送", title: "zs", value: "CrmWeb/CRMGL/DXFS/CRMGL_DXFS.aspx" },
     { id: 1163, pId: 110, name: "人员信息定义", title: "zs", value: "CrmWeb/CRMGL/RYXXDY/CRMGL_RYXXDY_Srch.aspx" },
     { id: 1163, pId: 110, name: "业务员信息定义", title: "zs", value: "CrmWeb/CRMGL/YWYDY/CRMGL_YWYDY_Srch.aspx" },
            { id: 1101, pId: 110, name: "SAMPLE", title: "ys", value: "CrmWeb/HYKGL/SAMPLE/SAMPLE.aspx" },
    { id: 116, pId: 11, name: "库存卡管理", title: "1" },
     { id: 1129, pId: 116, name: "会员卡建卡", title: "zs", value: "CrmWeb/HYKGL/HYKJK/HYKGL_HYKJK_Srch.aspx?czk=0" },
      { id: 1129, pId: 116, name: "会员卡制卡", title: "zs", value: "CrmWeb/HYKGL/HYKJKZK/HYKGL_HYKJKZK.aspx?action=add" },
       { id: 1129, pId: 116, name: "会员卡验卡（总部库）", title: "zs", value: "CrmWeb/HYKGL/KCKXXYZ/HYKGL_KCKXXYZ.aspx?old=0" },
       { id: 1129, pId: 116, name: "会员卡验卡（制卡库）", title: "zs", value: "CrmWeb/HYKGL/KCKXXYZ/HYKGL_KCKXXYZ.aspx?old=1" },
       //{ id: 1129, pId: 116, name: "会员卡验卡（总部）", title: "zs", value: "CrmWeb/HYKGL/KCKXXYZ/HYKGL_KCKXXYZ.aspx?" },
     { id: 1111, pId: 116, name: "会员卡领取", title: "ys", value: "CrmWeb/HYKGL/HYKLQ/HYKGL_HYKLQ_Srch.aspx?czk=0&djlx=0" },
     { id: 1111, pId: 116, name: "会员卡调拨", title: "ys", value: "CrmWeb/HYKGL/HYKLQ/HYKGL_HYKLQ_Srch.aspx?czk=0&djlx=1" },
     { id: 1111, pId: 116, name: "会员卡退领", title: "ys", value: "CrmWeb/HYKGL/HYKLQ/HYKGL_HYKLQ_Srch.aspx?czk=0&djlx=2" },
     { id: 1139, pId: 116, name: "库存卡作废", title: "zs", value: "CrmWeb/HYKGL/KCKZF/KCHYKGL_KCKZF_Srch.aspx?hf=0" },
     { id: 1139, pId: 116, name: "库存卡作废恢复", title: "zs", value: "CrmWeb/HYKGL/KCKZF/KCHYKGL_KCKZF_Srch.aspx?hf=1" },
     { id: 1139, pId: 116, name: "库存卡金额调整", title: "zs", value: "CrmWeb/HYKGL/KCKYETZ/HYKGL_KCKYETZ_Srch.aspx" },
     { id: 1139, pId: 116, name: "库存会员卡查询", title: "zs", value: "CrmWeb/HYKGL/KCKCX/HYKGL_KCKCX_Srch.aspx?czk=0" },
     { id: 1139, pId: 116, name: "库存会员卡保管帐", title: "zs", value: "CrmWeb/HYKGL/KCKBGZ/HYKGL_KCKBGZ_Srch.aspx?czk=0" },
     { id: 11116, pId: 116, name: "库存会员卡报表", title: "zy", value: "CrmWeb/HYKGL/KCKBB/HYKGL_HYKKCBB_Srch.aspx?czk=0" },
     { id: 1139, pId: 116, name: "库存面值卡查询", title: "zs", value: "CrmWeb/HYKGL/KCKCX/HYKGL_KCKCX_Srch.aspx?czk=1" },
     { id: 1139, pId: 116, name: "库存面值卡保管帐", title: "zs", value: "CrmWeb/HYKGL/KCKBGZ/HYKGL_KCKBGZ_Srch.aspx?czk=1" },
     { id: 11116, pId: 116, name: "库存面值卡报表", title: "zy", value: "CrmWeb/HYKGL/KCKBB/HYKGL_HYKKCBB_Srch.aspx?czk=1" },
     { id: 1139, pId: 116, name: "制卡信息查询", title: "zs", value: "CrmWeb/HYKGL/ZKXX/HYKGL_ZKXX_Srch.aspx" },
     { id: 1139, pId: 116, name: "库存会员卡有效期变更", title: "zs", value: "CrmWeb/HYKGL/KCKYXQBD/HYKGL_KCKYXQBD_Srch.aspx?czk=0" },
       { id: 1139, pId: 116, name: "库存面值卡盘点", title: "gx", value: "CrmWeb/HYKGL/KCMZKPD/HYKGL_KCMZKPD_Srch.aspx?czk=1" },
     { id: 1139, pId: 116, name: "查询发券记录", title: "zs", value: "CrmWeb/HYKGL/CXFQJL/HYKGL_CXFQJL_Srch.aspx" },
     { id: 1139, pId: 116, name: "顾客卡交易冲正处理", title: "zs", value: "CrmWeb/MZKGL/CZKCZCL/MZKGL_CZKCZCL_Srch.aspx" },
     { id: 1139, pId: 116, name: "金额帐日报表", title: "zs", value: "CrmWeb/HYKGL/JEZRBB/HYKGL_JEZRBB_Srch.aspx" },
     { id: 1139, pId: 116, name: "金额帐月报表", title: "zs", value: "CrmWeb/HYKGL/JEZYBB/HYKGL_JEZYBB_Srch.aspx" },
     { id: 1139, pId: 116, name: "金额帐余额查询", title: "zs", value: "CrmWeb/HYKGL/JEZYECX/HYKGL_JEZYECX_Srch.aspx" },


   { id: 119, pId: 11, name: "移动端平台", title: "1" },
      { id: 1123, pId: 119, name: "微信菜单定义", title: "", value: "CrmWeb/GTPT/WXCDDY/GTPT_WXCDDY.aspx" },
      //{ id: 1123, pId: 119, name: "微信分组定义", title: "分组定义", value: "CrmWeb/GTPT/WXGROUP/GTPT_WXGROUP_Srch.aspx" },
      //{ id: 1123, pId: 119, name: "微信用户分组操作", title: "分组操作", value: "CrmWeb/GTPT/WXUSER_GROUP/GTPT_WXUSER_GROUP_Srch.aspx" },
        //{ id: 1123, pId: 119, name: "微信资源定义", title: "群发消息", value: "CrmWeb/GTPT/WXRESOURCE/GTPT_WXRESOURCE_Srch.aspx" },
   { id: 1123, pId: 119, name: "微信首页导航定义", title: "", value: "CrmWeb/GTPT/WXSYDHDY/GTPT_SYDHDY_Srch.aspx" },


      { id: 1123, pId: 119, name: "移动端品牌商标定义", title: "", value: "CrmWeb/GTPT/WXPPSBDY/GTPT_WXPPSBDY_Srch.aspx" },
      { id: 1123, pId: 119, name: "移动端楼层定义", title: "", value: "CrmWeb/GTPT/WXLCDY/GTPT_WXLCDY_Srch.aspx" },
      { id: 1123, pId: 119, name: "移动端门店定义", title: "", value: "CrmWeb/GTPT/WXMDDY/GTPT_WXMDDY_Srch.aspx" },
      { id: 1123, pId: 119, name: "移动端品牌分类定义", title: "", value: "CrmWeb/GTPT/WXFL/GTPT_WXFL_Srch.aspx" },
      { id: 1123, pId: 119, name: "移动端商品推荐定义", title: "", value: "CrmWeb/GTPT/WXSPTJDY/GTPT_WXSPTJDY_Srch.aspx" },
      { id: 1123, pId: 119, name: "微信解绑", title: "", value: "CrmWeb/GTPT/WXJB/GTPT_WXJB_Srch.aspx" },
      { id: 1123, pId: 119, name: "微信会员权益定义", title: "", value: "CrmWeb/GTPT/HYQYDY/GTPT_HYQYDY_Srch.aspx" },
      { id: 1123, pId: 119, name: "微信联盟商户类型定义", title: "", value: "CrmWeb/GTPT/WXSHLMLXDY/GTPT_WXSHLMLXDY_Srch.aspx" },
      { id: 1123, pId: 119, name: "微信商户联盟定义", title: "", value: "CrmWeb/GTPT/WXSHLMDY/GTPT_WXSHLMDY_Srch.aspx" },
      { id: 1123, pId: 119, name: "移动端楼层商标定义", title: "", value: "CrmWeb/GTPT/WXLCSBDY/GTPT_WXLCSBDY_Srch.aspx" },
      { id: 1123, pId: 119, name: "促销活动定义", title: "", value: "CrmWeb/GTPT/CXHDDY/GTPT_CXHDDY_Srch.aspx" },

      { id: 1123, pId: 119, name: "微信送券规则定义", title: "", value: "CrmWeb/GTPT/WXSQGZDY/GTPT_WXSQGZDY_Srch.aspx" },
      { id: 1123, pId: 119, name: "送券活动定义单", title: "", value: "CrmWeb/GTPT/WXSQGZDYD/GTPT_WXSQGZDYD_Srch.aspx" },

      { id: 1123, pId: 119, name: "微信礼包发放规则定义", title: "", value: "CrmWeb/GTPT/WXLPFFGZDY/GTPT_WXLPFFGZDY_Srch.aspx" },
      { id: 1123, pId: 119, name: "微信抽奖定义单", title: "", value: "CrmWeb/GTPT/WXCJDYD/GTPT_WXCJDDY_Srch.aspx?djlx=2" },
      { id: 1123, pId: 119, name: "微信抢红包定义单", title: "", value: "CrmWeb/GTPT/WXCJDYD/GTPT_WXCJDDY_Srch.aspx?djlx=1" },
      { id: 1123, pId: 119, name: "微信刮刮卡定义单", title: "", value: "CrmWeb/GTPT/WXCJDYD/GTPT_WXCJDDY_Srch.aspx?djlx=3" },

      { id: 1123, pId: 119, name: "微信签到送积分规则定义", title: "", value: "CrmWeb/GTPT/WXQDSJFGZDY/GTPT_WXQDSJFGZDY_Srch.aspx" },
      { id: 1123, pId: 119, name: "微信礼包定义", title: "", value: "CrmWeb/GTPT/WXLBDY/GTPT_WXLBDY_Srch.aspx" },
      { id: 1123, pId: 119, name: "微信开卡赠送积分规则定义", title: "", value: "CrmWeb/GTPT/WXKKZSJFGZDY/GTPT_WXKKZSJFGZDY_Srch.aspx?gzlx=1" },
      { id: 1123, pId: 119, name: "微信绑卡赠送积分规则定义", title: "", value: "CrmWeb/GTPT/WXKKZSJFGZDY/GTPT_WXKKZSJFGZDY_Srch.aspx?gzlx=2" },
      { id: 1123, pId: 119, name: "微调查内容题库定义", title: "", value: "CrmWeb/GTPT/WDCNRTKDY/GTPT_WDCNRTKDY_Srch.aspx" },
      { id: 1123, pId: 119, name: "微调查定义单", title: "", value: "CrmWeb/GTPT/WDCDY/GTPT_WDCDY_Srch.aspx" },
      { id: 1123, pId: 119, name: "微调查结果统计", title: "", value: "CrmWeb/GTPT/WDCJGTJ/GTPT_WDCJGTJ_Srch.aspx" },
      { id: 1123, pId: 119, name: "微调查明细查询", title: "", value: "CrmWeb/GTPT/WDCXXJLCX/GTPT_WDCXXJLCX_Srch.aspx" },
      { id: 1123, pId: 119, name: "投诉类型定义", title: "", value: "CrmWeb/GTPT/TSLXDY/GTPT_TSLXDY.aspx" },
      { id: 1123, pId: 119, name: "微信投诉记录", title: "", value: "CrmWeb/GTPT/WXTSJL/GTPT_WXTSJL_Srch.aspx" },
      { id: 1123, pId: 119, name: "微信绑定会员统计", title: "", value: "CrmWeb/GTPT/WXBDHYTJ/GTPT_WXBDHYTJ_Srch.aspx" },
      { id: 1123, pId: 119, name: "微信关注功能分析", title: "", value: "CrmWeb/GTPT/WXGZGNFX/GTPT_WXGZGNFX_Srch.aspx" },
      { id: 1123, pId: 119, name: "按卡类型分析微信绑定会员", title: "", value: "CrmWeb/GTPT/AKLXFXWXBDHY/GTPT_AKLXFXWXBDHY_Srch.aspx" },
      { id: 1123, pId: 119, name: "微信用户关注分析", title: "", value: "CrmWeb/GTPT/WXYHGZFX/GTPT_WXYHGZFX_Srch.aspx" },
      { id: 1123, pId: 119, name: "微信关键词触发记录查询", title: "", value: "CrmWeb/GTPT/WXGJCCFJLCX/GTPT_WXGJCCFJLCX_Srch.aspx" },
      { id: 1123, pId: 119, name: "微信用户查询", title: "", value: "CrmWeb/GTPT/WXYHCX/GTPT_WXYHCX_Srch.aspx" },
      { id: 1123, pId: 119, name: "微信奖品发放记录查询", title: "", value: "CrmWeb/GTPT/WXJPFFJLCX/GTPT_WXJPFFJLCX_Srch.aspx" },
      { id: 1123, pId: 119, name: "微信问题定义", title: "", value: "CrmWeb/GTPT/WXWTDY/GTPT_WXWTDY_Srch.aspx" },
      { id: 1123, pId: 119, name: "微信分享定义", title: "", value: "CrmWeb/GTPT/WXFXDY/GTPT_WXFXDY_Srch.aspx" },
      { id: 1123, pId: 119, name: "微调查用户查询", title: "", value: "CrmWeb/GTPT/WDCYHCX/GTPT_WDCYHCX_Srch.aspx" },
      { id: 1123, pId: 119, name: "微调查赠礼记录查询", title: "", value: "CrmWeb/GTPT/WDCZLJLCX/GTPT_WDCZLJLCX_Srch.aspx" },
      { id: 1123, pId: 119, name: "移动端最新活动定义", title: "", value: "CrmWeb/GTPT/WXZXHDDY/GTPT_WXZXHDDY_Srch.aspx" },
      { id: 1123, pId: 119, name: "微信奖品级次定义", title: "", value: "CrmWeb/GTPT/WXJPJCDY/GTPT_WXJPJCDY.aspx" },
      { id: 1123, pId: 119, name: "微信领奖单", title: "", value: "CrmWeb/GTPT/WXLJD/GTPT_WXLJD_Srch.aspx" },
      { id: 1123, pId: 119, name: "微信送券记录查询", title: "", value: "CrmWeb/GTPT/WXSQJLCX/GTPT_WXSQJLCX_Srch.aspx" },
      { id: 1123, pId: 119, name: "微信开卡绑卡赠礼记录查询", title: "", value: "CrmWeb/GTPT/WXKKBKZLJLCX/GTPT_WXKKBKZLJLCX_Srch.aspx" },
      { id: 1123, pId: 119, name: "微信预约服务定义", title: "", value: "CrmWeb/GTPT/WXYYFWDY/GTPT_WXYYFWDY_Srch.aspx" },
      { id: 1123, pId: 119, name: "微信预约服务记录查询", title: "", value: "CrmWeb/GTPT/WXYYFWJLCX/GTPT_WXYYFWJLCX_Srch.aspx" },
      { id: 1123, pId: 119, name: "微信预约服务处理", title: "", value: "CrmWeb/GTPT/WXYYFWJLCL/GTPT_WXYYFWJLCL_Srch.aspx" },
      { id: 1123, pId: 119, name: "会员卡图片上传", title: "", value: "CrmWeb/GTPT/HYKTPSC/GTPT_HYKTPSC.aspx" },
      { id: 1123, pId: 119, name: "微信开绑卡图片上传", title: "", value: "CrmWeb/GTPT/WXTPSC/GTPT_WXTPSC.aspx" },
      //{ id: 1123, pId: 119, name: "微信开卡绑卡查询", title: "", value: "CrmWeb/GTPT/KKBK_Srch/GTPT_KKBK_Srch.aspx" },
      //{ id: 1123, pId: 119, name: "微信开卡绑卡增积分查询", title: "", value: "CrmWeb/GTPT/KBKSJFCX/GTPT_KBKSJF_Srch.aspx" },
      //{ id: 1123, pId: 119, name: "微信开卡绑卡推荐人查询", title: "", value: "CrmWeb/GTPT/KBKTJRCX/GTPT_KBKTJR_Srch.aspx" },
      //{ id: 1123, pId: 119, name: "移动端品牌折扣定义单", title: "", value: "CrmWeb/GTPT/SBZKDYD/GTPT_SBZKDYD_Srch.aspx" },
      //{ id: 1123, pId: 119, name: "移动端广告定义", title: "", value: "CrmWeb/GTPT/GGDY/GTPT_GGDY_Srch.aspx" },
      //{ id: 1123, pId: 119, name: "移动端个性化符号定义", title: "", value: "CrmWeb/GTPT/WXGXHFHDY/GTPT_GXHFHDY.aspx" },
      { id: 1123, pId: 119, name: "城市定义", title: "", value: "CrmWeb/GTPT/CSDY/GTPT_CSDY.aspx" },
      { id: 1123, pId: 119, name: "微信关注回复", title: "", value: "CrmWeb/GTPT/WXGZHF/GTPT_WXGZHF_Srch.aspx?type=2" },
      { id: 1123, pId: 119, name: "微信默认回复", title: "", value: "CrmWeb/GTPT/WXGZHF/GTPT_WXGZHF_Srch.aspx?type=3" },
      { id: 1123, pId: 119, name: "微信关键字回复", title: "", value: "CrmWeb/GTPT/WXGZHF/GTPT_WXGZHF_Srch.aspx?type=0" },
      { id: 1123, pId: 119, name: "微信菜单推送回复", title: "", value: "CrmWeb/GTPT/WXGZHF/GTPT_WXGZHF_Srch.aspx?type=1" },
      { id: 1123, pId: 119, name: "礼品图片上传", title: "", value: "CrmWeb/GTPT/LPTPSC/GTPT_LPTPSC_Srch.aspx" },
      { id: 1123, pId: 119, name: "编码券定义", title: "zs", value: "CrmWeb/GTPT/BMQDY/APP_BMQDY_Srch.aspx" },
      { id: 1123, pId: 119, name: "编码券发放规则定义", title: "ys", value: "CrmWeb/GTPT/BMQFFGZDY/APP_BMQFFGZDY_Srch.aspx" },
      { id: 1123, pId: 119, name: "编码券礼包定义", title: "ys", value: "CrmWeb/GTPT/BMQLBDEF/GTPT_BMQLBDEF_Srch.aspx" },
      { id: 1123, pId: 119, name: "编码券发放单", title: "ys", value: "CrmWeb/GTPT/BMQFFD/APP_BMQFFD_Srch.aspx" },
      { id: 1123, pId: 119, name: "微信消耗积分明细查询", title: "", value: "CrmWeb/GTPT/WXXHJFMXCX/GTPT_WXXHJFMXCX_Srch.aspx" },
      { id: 1123, pId: 119, name: "微信中奖会员名单查询", title: "", value: "CrmWeb/GTPT/WXZJHYMDCX/GTPT_WXZJHYMDCX_Srch.aspx" },
      { id: 1123, pId: 119, name: "微信签到赠送积分明细查询", title: "", value: "CrmWeb/GTPT/QDJLCX/GTPT_QDJLCX_Srch.aspx" },
      { id: 1123, pId: 119, name: "积分兑换礼品规则定义", title: "", value: "CrmWeb/GTPT/JFDHLPGZDY/GTPT_JFDHLPGZDY_Srch.aspx" },
      { id: 1123, pId: 119, name: "积分兑换礼品定义单", title: "", value: "CrmWeb/GTPT/JFDHLPDYD/GTPT_JFDHLPDYD_Srch.aspx" },
      { id: 1123, pId: 119, name: "微信积分兑换礼品领取单", title: "", value: "CrmWeb/GTPT/WXJFDHLPLQD/GTPT_WXJFDHLPLQD_Srch.aspx" },
      //{ id: 1123, pId: 119, name: "微信积分兑换礼品单", title: "", value: "CrmWeb/GTPT/WXJFDHLPD/GTPT_WXJFDHLPD_Srch.aspx" },
      { id: 1123, pId: 119, name: "微信积分兑换优惠券单", title: "", value: "CrmWeb/GTPT/WXJFDHYHQ/GTPT_WXJFDHYHQ_Srch.aspx" },

      { id: 1123, pId: 119, name: "钱买券规则定义单", title: "", value: "CrmWeb/GTPT/QMQGZDYD/GTPT_QMQGZDYD_Srch.aspx" },
      { id: 1123, pId: 119, name: "钱买券记录查询", title: "", value: "CrmWeb/GTPT/WXQMQJLCX/GTPT_WXQMQJLCX_Srch.aspx" },
      { id: 1123, pId: 119, name: "钱买券后台退款", title: "", value: "CrmWeb/GTPT/QMQTH/GTPT_QMQTH_Srch.aspx" },
      { id: 1123, pId: 119, name: "媒体文件素材定义", title: "", value: "CrmWeb/GTPT/MEDIADY/GTPT_MEDIADY_Srch.aspx" },
      { id: 1123, pId: 119, name: "图文素材定义", title: "", value: "CrmWeb/GTPT/NEWSDY/GTPT_NEWSDY_Srch.aspx" },
      { id: 1123, pId: 119, name: "微信标签定义", title: "", value: "CrmWeb/GTPT/WXBQDY/GTPT_WXBQDY.aspx" },
     // { id: 1123, pId: 119, name: "微信粉丝管理", title: "", value: "CrmWeb/GTPT/HQBQXFS/GTPT_HQBQXFS.aspx" },
      { id: 1123, pId: 119, name: "微信黑名单管理", title: "", value: "CrmWeb/GTPT/HQHMD/GTPT_HQHMD.aspx" },
      { id: 1123, pId: 119, name: "微信会员批量打标签", title: "", value: "CrmWeb/GTPT/HYPLDBQ/GTPT_HYPLDBQ.aspx" },
      { id: 1123, pId: 119, name: "微信群发消息", title: "", value: "CrmWeb/GTPT/WXQFXXDY/GTPT_WXQFXXDY_Srch.aspx" },
      { id: 1123, pId: 119, name: "微信卡券包会员卡定义", title: "", value: "CrmWeb/GTPT/WXKLXDY/GTPT_WXKLXDY_Srch.aspx" },
      { id: 1123, pId: 119, name: "微信卡包会员卡投放设置", title: "", value: "CrmWeb/GTPT/WXKBHYKTF/GTPT_WXKBHYKTF.aspx" },
      { id: 1123, pId: 119, name: "积分兑换比例规则定义", title: "ys", value: "CrmWeb/GTPT/JFDHBLDY/GTPT_JFDHBLDY_Srch.aspx" },


 { id: 111, pId: 11, name: "会员卡管理", title: "1" },
     { id: 1167, pId: 111, name: "保管地点定义", title: "zs", value: "CrmWeb/HYKGL/BGDDDY/HYKGL_BGDDDY.aspx" },
     { id: 1171, pId: 111, name: "会员卡升级规则定义", title: "ys", value: "CrmWeb/HYKGL/HYKSJJGZDY/HYKGL_HYKSJJGZDY_Srch.aspx?sj=1" },
     { id: 1172, pId: 111, name: "会员卡降级规则定义", title: "ys", value: "CrmWeb/HYKGL/HYKSJJGZDY/HYKGL_HYKSJJGZDY_Srch.aspx?sj=0" },
     { id: 1112, pId: 111, name: "会员卡发放查询", title: "ys", value: "CrmWeb/HYKGL/HYKFF/HYKGL_HYKFF_Srch.aspx" },
     { id: 1112, pId: 111, name: "会员卡发放", title: "ys", value: "CrmWeb/HYKGL/HYKFF/HYKGL_HYKFF.aspx?action=add" },
     { id: 1112, pId: 111, name: "会员卡快速发放", title: "ys", value: "CrmWeb/HYKGL/HYKFF/HYKGL_HYKFF_Fast.aspx" },
     { id: 1113, pId: 111, name: "批量会员卡发放", title: "ys", value: "CrmWeb/HYKGL/HYKFF/HYKGL_PLHYKFF_Srch.aspx" },
     { id: 1112, pId: 111, name: "会员信息属性内容定义", title: "ys", value: "CrmWeb/CRMGL/HYXXXM/CRMGL_HYXXXM.aspx" },
     { id: 11111, pId: 111, name: "会员档案录入查询", title: "ys", value: "CrmWeb/HYKGL/HYDALR/HYKGL_HYDALR_Srch.aspx" },
     { id: 1114, pId: 111, name: "会员卡操作台", title: "1", value: "CrmWeb/HYKGL/HYKCZT/HYKCZT_FW.aspx" },
     { id: 1115, pId: 111, name: "会员信息查询", title: "ys", value: "CrmWeb/HYKGL/HYXX/HYKGL_HYXX_Srch.aspx" },
     { id: 1117, pId: 111, name: "会员卡换卡", title: "1", value: "CrmWeb/HYKGL/HYKHK/HYKGL_HYKHK_Srch.aspx?mzk=0&djlx=0" },
     { id: 1118, pId: 111, name: "会员卡挂失", title: "1", value: "CrmWeb/HYKGL/HYKGS/HYKGL_HYKGS_Srch.aspx?hf=0&czk=0" },
     { id: 1118, pId: 111, name: "会员卡挂失恢复", title: "1", value: "CrmWeb/HYKGL/HYKGS/HYKGL_HYKGS_Srch.aspx?hf=1&czk=0" },
     //{ id: 1119, pId: 111, name: "会员卡挂失恢复", title: "1", value: "CrmWeb/HYKGL/HYKGS/HYKGL_HYKGS_Srch.aspx?param=1" },
     { id: 1120, pId: 111, name: "更换卡类型", title: "1", value: "CrmWeb/HYKGL/GHKLX/HYKGL_GHKLX_Srch.aspx" },
     { id: 1121, pId: 111, name: "有效期延长", title: "1", value: "CrmWeb/HYKGL/YXQYC/HYKGL_YXQYC_Srch.aspx" },
     { id: 1121, pId: 111, name: "状态变动单", title: "1", value: "CrmWeb/HYKGL/ZTBD/HYKGL_ZTBD_Srch.aspx?czk=0" },
     { id: 1121, pId: 111, name: "更换发行单位", title: "1", value: "CrmWeb/HYKGL/GHFXDW/HYKGL_GHFXDW_Srch.aspx" },
    { id: 1115, pId: 111, name: "Excel导入会员信息", title: "ys", value: "CrmWeb/HYKGL/HYDADR/HYKGL_HYDADR.aspx" },
    { id: 11117, pId: 111, name: "库存卡信息导出", title: "ys", value: "CrmWeb/HYKGL/KCKCX/ExportKCKXX.aspx" },
     //{ id: 1115, pId: 111, name: "Excel批量卡发放", title: "1", value: "CrmWeb/SrchHYXX/SrchHYXX.aspx" },
      { id: 1123, pId: 111, name: "已升级会员查询", title: "zs", value: "   CrmWeb/HYKGL/YSJHYCX/HYKGL_YSJHYCX_Srch.aspx" },
      { id: 1123, pId: 111, name: "会员卡可升级记录查询", title: "zs", value: "   CrmWeb/HYKGL/HYKKSJJL/HYKGL_HYKKSJJL_Srch.aspx" },
      { id: 1123, pId: 111, name: "会员卡升级", title: "zs", value: "   CrmWeb/HYKGL/HYKSJ/HYKGL_HYKSJ_Srch.aspx?sj=1" },
     { id: 1124, pId: 111, name: "会员卡降级", title: "zs", value: "   CrmWeb/HYKGL/HYKSJ/HYKGL_HYKSJ_Srch.aspx?sj=0" },
       { id: 1123, pId: 111, name: "库存卡补磁", title: "zs", value: "   CrmWeb/HYKGL/KCKBC/HYKGL_KCKBC.aspx?hyk=0&czk=0" },
     { id: 1124, pId: 111, name: "会员卡补磁", title: "zs", value: "   CrmWeb/HYKGL/KCKBC/HYKGL_KCKBC.aspx?hyk=1&czk=0" },
     { id: 1125, pId: 111, name: "优惠券账户存款", title: "ys", value: "CrmWeb/HYKGL/YHQCK/HYKGL_YHQCK_Srch.aspx" },
      { id: 1141, pId: 111, name: "优惠券账户批量存款", title: "ys", value: "CrmWeb/HYKGL/YHQPLCK/HYKGL_YHQPLCK_Srch.aspx" },
       { id: 1141, pId: 111, name: "优惠券账户批量取款", title: "ys", value: "CrmWeb/HYKGL/YHQPLQK/HYKGL_YHQPLQK_Srch.aspx" },
     { id: 11110, pId: 111, name: "优惠券账户取款", title: "ys", value: "CrmWeb/HYKGL/YHQQK/HYKGL_YHQQK_Srch.aspx" },
     { id: 1126, pId: 111, name: "优惠券账户转储", title: "zs", value: "CrmWeb/HYKGL/YHQZC/HYKGL_YHQZC_Srch.aspx" },
     { id: 11260, pId: 111, name: "优惠券日报表", title: "zs", value: "CrmWeb/HYKGL/YHQBB/HYKGL_YHQRBB.aspx?DJLX=0" },
     { id: 11261, pId: 111, name: "优惠券月报表", title: "zs", value: "CrmWeb/HYKGL/YHQBB/HYKGL_YHQRBB.aspx?DJLX=1" },
     { id: 11261, pId: 111, name: "优惠券年报表", title: "zs", value: "CrmWeb/HYKGL/YHQBB/HYKGL_YHQRBB.aspx?DJLX=2" },
     { id: 11261, pId: 111, name: "优惠券门店日报表", title: "zs", value: "CrmWeb/HYKGL/YHQMDRBB/HYKGL_YHQMDRBB_Srch.aspx" },
     { id: 11261, pId: 111, name: "优惠券消费统计实时查询", title: "zs", value: "CrmWeb/HYKGL/YHQSSXFTJ/HYKGL_YHQSSXFTJ_Srch.aspx" },
     { id: 11261, pId: 111, name: "按日期统计会员卡优惠券消费", title: "zs", value: "CrmWeb/HYKGL/HYKYHQXFTJ/HYKGL_HYKYHQXFTJ_Srch.aspx" },
     { id: 11261, pId: 111, name: "按门店统计会员卡优惠券消费", title: "zs", value: "CrmWeb/HYKGL/HYKYHQXFTJMD/HYKGL_HYKYHQXFTJMD_Srch.aspx" },
     { id: 11261, pId: 111, name: "按商户统计会员卡优惠券消费", title: "zs", value: "CrmWeb/HYKGL/HYKYHQXFTJSH/HYKGL_HYKYHQXFTJSH_Srch.aspx" },
     { id: 11261, pId: 111, name: "会员卡优惠券前台处理统计", title: "zs", value: "CrmWeb/HYKGL/HYKYHQQTCLTJ/HYKGL_HYKYHQQTCLTJ_Srch.aspx" },
     { id: 1127, pId: 111, name: "会员卡作废", title: "zs", value: "CrmWeb/HYKGL/HYKZF/HYKGL_HYKZF_Srch.aspx" },
     { id: 1127, pId: 111, name: "会员卡回收", title: "zs", value: "CrmWeb/HYKGL/HYKHS/HYKGL_HYKHS_Srch.aspx" },
     { id: 1134, pId: 111, name: "优惠券余额清零", title: "zs", value: "CrmWeb/HYKGL/YHQYEQL/HYKGL_YHQYEQL_Srch.aspx" },
     { id: 1134, pId: 111, name: "变更优惠券有效期", title: "zs", value: "CrmWeb/HYKGL/YHQYXQBD/HYKGL_YHQYXQBD_Srch.aspx" },
     { id: 1134, pId: 111, name: "会员卡发售统计", title: "zs", value: "CrmWeb/HYKGL/HYKTJ/HYKGL_HYKTJ_Srch.aspx" },
     { id: 1135, pId: 111, name: "会员密码修改", title: "zs", value: "CrmWeb/HYKGL/HYMMXG/HYKGL_HYMMXG_Srch.aspx?iTYPE=0" },
     { id: 1135, pId: 111, name: "会员密码重置", title: "zs", value: "CrmWeb/HYKGL/HYMMXG/HYKGL_HYMMXG_Srch.aspx?iTYPE=1" },
     { id: 11116, pId: 111, name: "会员卡金额账户处理记录查询", title: "zy", value: "CrmWeb/HYKGL/HYKJEZHCLJL/HYKGL_HYKJEZHCLJL_Srch.aspx?czk=0" },
     { id: 11116, pId: 111, name: "会员卡积分日报表", title: "zy", value: "CrmWeb/HYKGL/HYKJFRBB/HYKGL_HYKJFRBB_Srch.aspx" },
     { id: 11116, pId: 111, name: "会员卡积分月报表", title: "zy", value: "CrmWeb/HYKGL/HYKJFYBB/HYKGL_HYKJFYBB_Srch.aspx" },
     { id: 11116, pId: 111, name: "按卡状态汇总查询卡信息", title: "zy", value: "CrmWeb/HYKGL/CXKXXBYZT/HYKGL_CXKXXBYZT_Srch.aspx" },
     { id: 11116, pId: 111, name: "会员卡状态变更规则定义", title: "zy", value: "CrmWeb/HYKGL/HYKZTBGGZDY/HYKGL_HYKZTBGGZDY.aspx" },
      { id: 11116, pId: 111, name: "会员", title: "zy", value: "CrmWeb/HYKGL/HYGXSHJFXF/HYKGL_HYGXSHJFXF_Srch.aspx" },
      { id: 11116, pId: 111, name: "优惠券账户处理记录查询", title: "ys", value: "CrmWeb/HYKGL/YHQZHCLJL/HYKGL_YHQZHCLJL_Srch.aspx" },
{ id: 1167, pId: 111, name: "门店保管地点定义", title: "zs", value: "CrmWeb/HYKGL/MDBGDDDY/HYKGL_MDBGDDDY.aspx" },
      { id: 1167, pId: 111, name: "会员推荐规则定义", title: "zs", value: "   CrmWeb/HYKGL/HYTJ/HYKGL_HYTJ_Srch.aspx" },
        { id: 1167, pId: 111, name: "会员推荐规则定义", title: "zs", value: "   CrmWeb/HYKGL/HYTJGZDY/HYKGL_HYTJGZDY_Srch.aspx" },
 { id: 1123, pId: 111, name: "优惠券账户明细查询", title: "zs", value: "   CrmWeb/HYKGL/YHQZHMX/HYKGL_YHQZHMX_Srch.aspx" },
  { id: 1123, pId: 111, name: "消费积分明细查询", title: "zs", value: "   CrmWeb/HYKGL/JFXFMX/HYKGL_JFXFMX_Srch.aspx" },
    { id: 1123, pId: 111, name: "积分变动查询", title: "zs", value: "   CrmWeb/HYKGL/JFBDJLMX/HYKGL_JFBDJLMX_Srch.aspx" },
     //{ id: 1123, pId: 111, name: "会员卡升级", title: "zs", value: "   CrmWeb/HYKGL/SJGZ/HYKGL_SJGZ_Srch.aspx" },
          { id: 1123, pId: 111, name: "会员卡领取", title: "ys", value: "CrmWeb/HYKGL/HYKLQ/HYKGL_HYKLQ_Srch.aspx?" },
          { id: 1123, pId: 111, name: "金额账存款处理", title: "ys", value: "CrmWeb/HYKGL/HYKCK/HYKGL_HYKCK_Srch.aspx" },
          { id: 1123, pId: 111, name: "金额账取款处理", title: "ys", value: "CrmWeb/HYKGL/HYKQK/HYKGL_HYKQK_Srch.aspx" },
           { id: 1123, pId: 111, name: "服务内容定义", title: "ys", value: "CrmWeb/HYKGL/FWNRDY/HYKGL_FWNRDY.aspx" },
           { id: 1123, pId: 111, name: "会员享受服务定义", title: "ys", value: "CrmWeb/HYKGL/HYXSFWDY/HYKGL_HYXSFWDY.aspx" },
           { id: 1123, pId: 111, name: "会员享受服务", title: "ys", value: "CrmWeb/HYKGL/FWXS/HYKGL_FWXS_Srch.aspx" },
           { id: 1123, pId: 111, name: "会员服务批量预存", title: "ys", value: "CrmWeb/HYKGL/HYFWPLYC/HYKGL_HYFWPLYC_Srch.aspx" },
           { id: 1123, pId: 111, name: "会员服务处理记录查询", title: "ys", value: "CrmWeb/HYKGL/FWCLCX/HYKGL_FWCLCX_Srch.aspx" },
           { id: 1123, pId: 111, name: "会员服务账户查询", title: "ys", value: "CrmWeb/HYKGL/FWZHCX/HYKGL_FWZH_Srch.aspx" },
                   { id: 1167, pId: 111, name: "长时间未消费会员查询", title: "ys", value: "CrmWeb/HYKGL/CSJWXFHYCX/HYKGL_CSJWXFHYCX_Srch.aspx" },
        { id: 1167, pId: 111, name: "会员资料不全查询", title: "ys", value: "CrmWeb/HYKGL/HYZLBQCX/HYKGL_HYZLBQCX_Srch.aspx" },
        { id: 1167, pId: 111, name: "会员恶意积分跟踪查询", title: "ys", value: "CrmWeb/HYKGL/EYJFGZCX/HYKGL_EYJFGZ_Srch.aspx" },
        { id: 1167, pId: 111, name: "未消费冻结卡查询", title: "ys", value: "CrmWeb/HYKGL/WXFDJKCX/HYKGL_WXFDJKCX_Srch.aspx" },
        { id: 1123, pId: 111, name: "会员卡可升级记录查询", title: "zs", value: "CrmWeb/HYKGL/HYKKSJJL/HYKGL_HYKKSJJL_Srch.aspx" },
        { id: 1123, pId: 111, name: "会员积分查询", title: "zs", value: "   CrmWeb/HYKGL/HYJFCX/HYKGL_HYJF_Srch.aspx" },
        { id: 1123, pId: 111, name: "会员品牌关联消费查询", title: "zs", value: "CrmWeb/HYKGL/GLDCX/HYKGL_GLD_Srch.aspx?PL=0" },
        { id: 1123, pId: 111, name: "会员品类关联消费查询", title: "zs", value: "CrmWeb/HYKGL/GLDCX/HYKGL_GLD_Srch.aspx?PL=1" },
        { id: 1123, pId: 111, name: "会员卡升降级规则查询", title: "zs", value: "CrmWeb/HYKGL/HYKSJJGZ/HYKGL_HYKSJJGZ_Srch.aspx" },
        { id: 1123, pId: 111, name: "门店积分对账", title: "zs", value: "CrmWeb/HYKGL/MDJFBB/HYKGL_MDJFBB_Srch.aspx" },
        { id: 1123, pId: 111, name: "服务享受情况查询", title: "zs", value: "CrmWeb/HYKGL/FWQKCX/HYKGL_FWQKCX_Srch.aspx" },
        { id: 1123, pId: 111, name: "金额账户汇总查询", title: "zs", value: "CrmWeb/HYKGL/HYKJEZHHZ/HYKGL_HYKJEZHHZ_Srch.aspx" },
        { id: 1123, pId: 111, name: "顾客重要档案修改", title: "zs", value: "CrmWeb/HYKGL/GKZYDALR/HYKGL_GKZYDALR_Srch.aspx" },
        { id: 1123, pId: 111, name: "联盟商户定义 ", title: "zs", value: "CrmWeb/HYKGL/LMSHDY/HYKGL_LMSHDY_Srch.aspx" },
        { id: 1123, pId: 111, name: "联盟商户基础信息定义 ", title: "zs", value: "CrmWeb/HYKGL/LMSHJCXXDY/HYKGL_LMSHJCXXDY.aspx" },
        { id: 1123, pId: 111, name: "联盟商户基础信息定义2 ", title: "zs", value: "CrmWeb/HYKGL/LMSHJCXXDY/TestGrid1.aspx" },
        { id: 1123, pId: 111, name: "联盟商户服务定义 ", title: "zs", value: "CrmWeb/HYKGL/LMSHFWDY/HYKGL_LMSHFWDY.aspx" },
        { id: 1123, pId: 111, name: "会员卡手机号码清理 ", title: "zs", value: "CrmWeb/HYKGL/QKSJHM/HYKGL_QKSJHM_Srch.aspx" },
        { id: 1123, pId: 111, name: "会员附属卡绑定 ", title: "zs", value: "CrmWeb/HYKGL/HYFSKBD/HYKGL_HYFSKBD_Srch.aspx" },
        { id: 1123, pId: 111, name: "联盟商户合同定义 ", title: "zs", value: "CrmWeb/HYKGL/LMSHHTDY/HYKGL_LMSHHTDY_Srch.aspx" },
        { id: 1123, pId: 111, name: "联盟商户费用录入 ", title: "zs", value: "CrmWeb/HYKGL/LMSHFYLR/HYKGL_LMSHFYLR_Srch.aspx" },
        { id: 1123, pId: 111, name: "联盟商户结算 ", title: "zs", value: "CrmWeb/HYKGL/LMSHJSD/HYKGL_LMSHJSD_Srch.aspx" },
        { id: 1167, pId: 111, name: "RFM会员查询", title: "zs", value: "CrmWeb/HYKGL/HYKRFM/HYKGL_HYKRFM_Srch.aspx" },
        { id: 1167, pId: 111, name: "会员卡生命周期", title: "zs", value: "CrmWeb/HYKGL/SMZQ/HYKGL_SMZQ_Srch.aspx" },
        { id: 1167, pId: 111, name: "生日会员统计", title: "zs", value: "CrmWeb/HYKGL/SRHYHZ/HYKGL_SRHYHZ_Srch.aspx" },
        { id: 1167, pId: 111, name: "已升级会员统计", title: "zs", value: "CrmWeb/HYKGL/YSJHYHZ/HYKGL_YSJHYHZ_Srch.aspx" },
        { id: 1167, pId: 111, name: "会员降级记录查询", title: "zs", value: "CrmWeb/HYKGL/HYSJJLCX/HYKGL_HYSJJLCX.aspx" },
       { id: 1167, pId: 111, name: "会员卡停用", title: "zs", value: "CrmWeb/HYKGL/HYKTY/HYKGL_HYKTY_Srch.aspx" },
       { id: 1167, pId: 111, name: "会员发送短信邮件", title: "zs", value: "CrmWeb/HYKGL/FSDXYJ/HYKGL_SENDMESSAGE_Srch.aspx" },
       { id: 1167, pId: 111, name: "退货会员预警查询", title: "zs", value: "CrmWeb/HYKGL/HYDHYJ/HYKGL_HYDHYJ_Srch.aspx" },
       { id: 1167, pId: 111, name: "检验金额帐余额正确性", title: "zs", value: "CrmWeb/HYKGL/YEZQXJC/HYKGL_YEZQXJC_Srch.aspx" },
       { id: 1167, pId: 111, name: "批量修改会员所属小区", title: "zs", value: "CrmWeb/HYKGL/PLXGHYXQ/HYKGL_PLXGHYXQ_Srch.aspx" },
       { id: 1167, pId: 111, name: "商标关联度查询", title: "zs", value: "CrmWeb/HYKGL/SBGLD/HYKGL_SBGLD_Srch.aspx" },
        { id: 1167, pId: 111, name: "金额转储", title: "ys", value: "CrmWeb/MZKGL/MZKJEZC/MZKGL_MZKJEZC_Srch.aspx" },
       { id: 1167, pId: 111, name: "编码券发放规则定义", title: "zs", value: "CrmWeb/HYKGL/BMQFFGZDY/LMSHGL_BMQFFGZDY_Srch.aspx" },
       { id: 1167, pId: 111, name: "编码券发放单", title: "zs", value: "CrmWeb/HYKGL/BMQFFD/LMSHGL_BMQFFD_Srch.aspx" },
       { id: 1123, pId: 111, name: "标签类别定义", title: "zs", value: "CrmWeb/HYKGL/BQLBDY/HYKGL_BQLBDY.aspx" },
       { id: 1123, pId: 111, name: "标签项目定义", title: "zs", value: "CrmWeb/HYKGL/BQXMDY/HYKGL_BQXMDY.aspx" },
       { id: 1123, pId: 111, name: "标签值定义", title: "zs", value: "CrmWeb/HYKGL/BQZDY/HYKGL_BQZDY.aspx" },
       { id: 1123, pId: 111, name: "会员批量打标签", title: "zs", value: "CrmWeb/HYKGL/HYPLDBQ/HYKGL_HYPLDBQ.aspx" },
       { id: 1123, pId: 111, name: "会员标签处理", title: "zs", value: "CrmWeb/HYKGL/HYDBQ/HYKGL_HYDBQ.aspx" },
       { id: 1167, pId: 111, name: "会员标签批量导入", title: "zs", value: "CrmWeb/HYKGL/HYBQPLDR/HYKGL_HYBQPLDR.aspx" },
       { id: 1167, pId: 111, name: "基础标签定义", title: "zs", value: "CrmWeb/HYKGL/JCBQGZDY/HYKGL_JCBQGZDY_Srch.aspx" },
       { id: 1167, pId: 111, name: "组合标签定义", title: "zs", value: "CrmWeb/HYKGL/ZHBQGZDY/HYKGL_ZHBQGZDY_Srch.aspx" },
       { id: 1167, pId: 111, name: "会员标签信息查询", title: "zs", value: "CrmWeb/HYKGL/BQHYCX/HYKGL_BQHY_Srch.aspx" },
       { id: 1167, pId: 111, name: "会员卡领用申请单", title: "zs", value: "CrmWeb/HYKGL/HYKLYSQ/HYKGL_HYKLYSQ_Srch.aspx?czk=0&djlx=0" },

    { id: 112, pId: 11, name: "会员消费管理", title: "1" },
     { id: 1129, pId: 112, name: "利群积分调整", title: "zs", value: "CrmWeb/HYXF/LQJFBD/HYXF_LQJFBD_Srch.aspx" },
     { id: 1129, pId: 112, name: "客群组类型定义", title: "zs", value: "CrmWeb/HYXF/HYZLXDY/HYXF_HYZLXDY.aspx" },
     { id: 1129, pId: 112, name: "客群组展示", title: "zs", value: "CrmWeb/HYXF/HYZLX/HYXF_HYZLX.aspx" },
     { id: 1129, pId: 112, name: "静态客群组定义", title: "zs", value: "CrmWeb/HYXF/HYZDY/HYXF_HYZDY_Srch.aspx?status=0" },
     { id: 1129, pId: 112, name: "动态客群组定义", title: "zs", value: "CrmWeb/HYXF/HYZDY/HYXF_HYZDY_Srch.aspx?status=1" },
     { id: 1128, pId: 112, name: "会员积分调整", title: "zs", value: "CrmWeb/HYXF/JFTZD/HYXF_JFTZD_Srch.aspx" },
     { id: 1124, pId: 112, name: "会员卡积分变动单", title: "1", value: "CrmWeb/HYXF/JFBDD/HYXF_JFBDD_Srch.aspx" },
     { id: 1133, pId: 112, name: "积分转储单", title: "zy", value: "CrmWeb/HYXF/JFZCD/HYXF_JFZCD_Srch.aspx" },
     { id: 1134, pId: 112, name: "积分定义单", title: "zy", value: "CrmWeb/HYXF/JFDYD/HYXF_JFDYD_Srch.aspx" },
     { id: 1135, pId: 112, name: "折扣定义单", title: "zy", value: "CrmWeb/HYXF/ZKDYD/HYXF_ZKDYD_Srch.aspx" },
      { id: 1133, pId: 112, name: "按商品查询商品积分情况", title: "zs", value: "CrmWeb/HYXF/SPJFXXCX/HYXF_SPJFXXCX_Srch.aspx" },
     { id: 1133, pId: 112, name: "积分返利规则定义", title: "zs", value: "CrmWeb/HYXF/JFFLGZDY/HYXF_JFFLGZDY_Srch.aspx" },
     { id: 1133, pId: 112, name: "积分返利执行(当前)", title: "zs", value: "CrmWeb/HYXF/HYJFCLZX/HYXF_HYJFCLZX_Srch.aspx?JFLX=1" },
     { id: 1133, pId: 112, name: "会员卡积分变动及处理记录查询", title: "zs", value: "CrmWeb/HYXF/HYKJFBDCLJL/HYXF_HYKJFBDCLJL_Srch.aspx" },
     { id: 1133, pId: 112, name: "会员消费明细查询", title: "zs", value: "CrmWeb/HYXF/HYXFMX/HYXF_HYXFMX_Srch.aspx?old=1" },
     { id: 1133, pId: 112, name: "会员退货记录查询", title: "zs", value: "CrmWeb/HYXF/HYXFMX/HYXF_HYXFMX_Srch.aspx?DJLX=1" },

     { id: 1133, pId: 112, name: "会员消费期间汇总", title: "zs", value: "CrmWeb/HYXF/HYXFQJHZ/HYXF_HYXFQJHZ_Srch.aspx" },
     { id: 1133, pId: 112, name: "会员消费明细一般列表", title: "zs", value: "CrmWeb/HYXF/HYXFMXLB/HYXF_HYXFMXLB_Srch.aspx" },
     { id: 1133, pId: 112, name: "部门消费情况汇总", title: "zs", value: "CrmWeb/HYXF/BMXFHZ/HYXF_BMXFHZ_Srch.aspx" },
     { id: 1133, pId: 112, name: "部门卡类型消费情况汇总", title: "zs", value: "CrmWeb/HYXF/BMKLXXFHZ/HYXF_BMKLXXFHZ_Srch.aspx" },
     { id: 1133, pId: 112, name: "部门品牌消费情况汇总", title: "zs", value: "CrmWeb/HYXF/BMPPXFHZ/HYXF_BMPPXFHZ_Srch.aspx" },
     { id: 1133, pId: 112, name: "会员退货买积分规则定义", title: "zs", value: "CrmWeb/HYXF/QMFDY/HYXF_QMFDY_Srch.aspx" },
     { id: 1133, pId: 112, name: "会员退货买积分", title: "zs", value: "CrmWeb/HYXF/QMF/HYXF_QMF_Srch.aspx" },
     { id: 1133, pId: 112, name: "会员退货买积分报表", title: "zs", value: "CrmWeb/HYXF/QMFBB/HYXF_QMFBB_Srch.aspx" },
     { id: 1121, pId: 112, name: "会员特定积分定义单", title: "ys", value: "CrmWeb/HYXF/TDJFZKD/HYXF_TDJFZKD_Srch.aspx?lx=0" },
     { id: 1122, pId: 112, name: "会员特定折扣定义单", title: "ys", value: "CrmWeb/HYXF/TDJFZKD/HYXF_TDJFZKD_Srch.aspx?lx=1" },
     { id: 1122, pId: 112, name: "积分返券汇总", title: "ys", value: "CrmWeb/HYXF/JFFQHZ/HYXF_JFFLFQHZ_Srch.aspx" },
     { id: 1122, pId: 112, name: "圈子类型定义", title: "ys", value: "CrmWeb/HYXF/QZLXDEF/HYXF_QZLXDEF_Srch.aspx" },
     { id: 1122, pId: 112, name: "圈子促销活动定义查询", title: "ys", value: "CrmWeb/HYXF/QZCXHD/HYXF_QZCXHD_Srch.aspx" },
     { id: 1122, pId: 112, name: "圈子信息定义", title: "ys", value: "CrmWeb/HYXF/QZXXDY/HYXF_QZXXDY_Srch.aspx" },
     { id: 1122, pId: 112, name: "积分汇总查询", title: "ys", value: "CrmWeb/HYXF/JFHZCX/HYXF_JFHZCX_Srch.aspx" },
      { id: 1122, pId: 112, name: "会员专享商品定义单", title: "ys", value: "CrmWeb/HYXF/HYZXSPDYD/HYXF_HYZXSPDYD_Srch.aspx" },
     { id: 1122, pId: 112, name: "供应商日期段内的每日积分", title: "ys", value: "CrmWeb/HYXF/GYSRQDNMRJF/HYXF_GYSRQDNMRJF.aspx" },


    { id: 113, pId: 11, name: "礼品管理", title: "1" },
     { id: 1135, pId: 113, name: "供货商定义", title: "zs", value: "CrmWeb/LPGL/GHSDY/LPGL_GHSDY.aspx" },
      //{ id: 1134, pId: 113, name: "礼品属性定义", title: "zs", value: "CrmWeb/LPGL/LPSXDY/LPGL_LPSXDY.aspx" },
      { id: 1134, pId: 113, name: "礼品分类定义", title: "zs", value: "CrmWeb/LPGL/LPFLDY/LPGL_LPFLDY.aspx" },
     { id: 1136, pId: 113, name: "礼品定义", title: "zs", value: "CrmWeb/LPGL/LPDY/LPGL_LPDY_Srch.aspx" },
     { id: 1131, pId: 113, name: "礼品进货单查询", title: "zs", value: "CrmWeb/LPGL/LPJHD/LPGL_LPJHD_Srch.aspx?iDJLX=0" },
     { id: 1131, pId: 113, name: "礼品退货单查询", title: "zs", value: "CrmWeb/LPGL/LPJHD/LPGL_LPJHD_Srch.aspx?iDJLX=1" },
     { id: 1132, pId: 113, name: "礼品领取单查询", title: "zs", value: "CrmWeb/LPGL/LPLQD/LPGL_LPLQD_Srch.aspx" },
     { id: 1133, pId: 113, name: "礼品库存查询", title: "zs", value: "CrmWeb/LPGL/JFFHLPKC/LPGL_JFFHLPKC_Srch.aspx" },//
     { id: 1133, pId: 113, name: "礼品进销存查询", title: "zs", value: "CrmWeb/LPGL/JFFHLPJXC/LPGL_JFFHLPJXC_Srch.aspx" },//
     { id: 1132, pId: 113, name: "礼品汇总查询", title: "zs", value: "CrmWeb/LPGL/JFFHLPHZ/LPGL_JFFHLPHZ_Srch.aspx" },//
     { id: 1132, pId: 113, name: "礼品库存变动明细", title: "zs", value: "CrmWeb/LPGL/LPKCBDJL/LPGL_LPKCBDJL_Srch.aspx" },//

     { id: 1137, pId: 113, name: "礼品发放规则", title: "zs", value: "CrmWeb/LPGL/LPFFGZ/LPGL_LPFFGZ_Srch.aspx" },
     { id: 1137, pId: 113, name: "满额赠礼规则", title: "zs", value: "CrmWeb/LPGL/LPZLGZ/LPGL_LPZLGZ_Srch.aspx" },
     { id: 1137, pId: 113, name: "未处理积分生日礼品发放", title: "zs", value: "CrmWeb/LPGL/LPFF/LPGL_LPFF_Srch.aspx?GZLX=5&JFLX=1" },
     { id: 1137, pId: 113, name: "日常礼品发放", title: "zs", value: "CrmWeb/LPGL/LPFF/LPGL_RCLPFF_Srch.aspx" },
     { id: 1137, pId: 113, name: "礼品发放活动定义", title: "zs", value: "CrmWeb/LPGL/LPFFHDDY/LPGL_LPFFHD_Srch.aspx" },
     { id: 1137, pId: 113, name: "活动礼品发放", title: "zs", value: "CrmWeb/LPGL/HDLPFF/LPGL_HDLPFF_Srch.aspx" },
     { id: 1137, pId: 113, name: "首刷礼品发放", title: "zs", value: "CrmWeb/LPGL/LPFF/LPGL_LPFF_Srch.aspx?GZLX=1" },
     { id: 1137, pId: 113, name: "办卡礼品发放", title: "zs", value: "CrmWeb/LPGL/LPFF/LPGL_LPFF_Srch.aspx?GZLX=2" },
     { id: 1137, pId: 113, name: "积分礼品发放", title: "zs", value: "CrmWeb/LPGL/LPFF/LPGL_LPFF_Srch.aspx?GZLX=3" },
     { id: 1137, pId: 113, name: "来店礼品发放", title: "zs", value: "CrmWeb/LPGL/LPFF/LPGL_LPFF_Srch.aspx?GZLX=4" },
     { id: 1137, pId: 113, name: "生日礼品发放", title: "zs", value: "CrmWeb/LPGL/LPFF/LPGL_LPFF_Srch.aspx?GZLX=5" },//&JFLX=0
     { id: 1132, pId: 113, name: "礼品报废处理", title: "zs", value: "CrmWeb/LPGL/LPZFCL/LPGL_LPZFCL_Srch.aspx" },//
     { id: 1132, pId: 113, name: "礼品盘点处理", title: "zs", value: "CrmWeb/LPGL/LPPDCL/LPGL_LPPDCL_Srch.aspx" },

    { id: 114, pId: 11, name: "面值卡管理", title: "1" },
     { id: 1140, pId: 114, name: "收款台监控日", title: "zs", value: "CrmWeb/MZKGL/SKTJKCSR/MZKGL_SKTJKCSR_Srch.aspx" },
     { id: 1140, pId: 114, name: "面值卡建卡", title: "zs", value: "CrmWeb/HYKGL/HYKJK/HYKGL_HYKJK_Srch.aspx?czk=1" },
     { id: 1140, pId: 114, name: "面值卡库存卡补磁", title: "zs", value: "CrmWeb/HYKGL/KCKBC/HYKGL_KCKBC.aspx?hyk=0&czk=1" },
     { id: 1140, pId: 114, name: "面值卡补磁", title: "zs", value: "CrmWeb/HYKGL/KCKBC/HYKGL_KCKBC.aspx?hyk=1&czk=1" },

     { id: 1140, pId: 114, name: "面值卡领取", title: "ys", value: "CrmWeb/HYKGL/HYKLQ/HYKGL_HYKLQ_Srch.aspx?czk=1&djlx=0" },
     { id: 1140, pId: 114, name: "面值卡调拨", title: "ys", value: "CrmWeb/HYKGL/HYKLQ/HYKGL_HYKLQ_Srch.aspx?czk=1&djlx=1" },
     { id: 1140, pId: 114, name: "面值卡退领", title: "ys", value: "CrmWeb/HYKGL/HYKLQ/HYKGL_HYKLQ_Srch.aspx?czk=1&djlx=2" },
     { id: 1140, pId: 114, name: "面值卡发售", title: "ys", value: "CrmWeb/MZKGL/MZKFS/MZKGL_MZKFS_Srch.aspx" },
     { id: 1140, pId: 114, name: "面值卡退售", title: "ys", value: "CrmWeb/MZKGL/MZKTS/MZKGL_MZKTS_Srch.aspx" },
     { id: 1140, pId: 114, name: "面值卡存款", title: "ys", value: "CrmWeb/MZKGL/CZKCK/MZKGL_CZKCK_Srch.aspx" },
     { id: 1141, pId: 114, name: "面值卡取款", title: "zs", value: "CrmWeb/MZKGL/CZKQK/MZKGL_CZKQK_Srch.aspx" },
     { id: 1140, pId: 114, name: "面值卡换卡", title: "1", value: "CrmWeb/MZKGL/MZKHK/MZKGL_MZKHK_Srch.aspx" },
     { id: 1140, pId: 114, name: "面值卡挂失", title: "1", value: "CrmWeb/MZKGL/MZKGS/MZKGL_MZKGS_Srch.aspx?hf=0&czk=1" },
     { id: 1140, pId: 114, name: "面值卡卡挂失恢复", title: "1", value: "CrmWeb/MZKGL/MZKGS/MZKGL_MZKGS_Srch.aspx?hf=1&czk=1" },
     { id: 1140, pId: 114, name: "库存面值卡有效期变更", title: "zs", value: "CrmWeb/MZKGL/KCKYXQBD/MZKGL_KCKYXQBD_Srch.aspx?old=0" },
     { id: 1129, pId: 114, name: "储值卡赠券规则", title: "ys", value: "CrmWeb/MZKDKHGL/CZKZKGZ/MZKDKHGL_CZKZKGZ.aspx?GZLX=0" },
     { id: 1129, pId: 114, name: "储值卡赠积分规则", title: "ys", value: "CrmWeb/MZKDKHGL/CZKZKGZ/MZKDKHGL_CZKZKGZ.aspx?GZLX=1" },
    // { id: 1129, pId: 114, name: "储值卡赠卡规则", title: "ys", value: "CrmWeb/MZKDKHGL/CZKZKGZ/MZKDKHGL_CZKZKGZ.aspx?GZLX=2" },
     { id: 1140, pId: 114, name: "面值卡批量存款", title: "1", value: "CrmWeb/MZKGL/MZKPLCK/MZKGL_MZKPLCK_Srch.aspx?" },
     { id: 1140, pId: 114, name: "面值卡批量取款", title: "1", value: "CrmWeb/MZKGL/MZKPLQK/MZKGL_MZKPLQK_Srch.aspx?" },
     { id: 1140, pId: 114, name: "面值卡支票批量启动", title: "ys", value: "CrmWeb/MZKGL/MZKZPPLQD/MZKGL_MZKZPPLQD_Srch.aspx" },
     { id: 1140, pId: 114, name: "面值卡欠款购销", title: "ys", value: "CrmWeb/MZKGL/MZKQKGX/MZKGL_MZKQKGX_Srch.aspx" },
     { id: 1140, pId: 114, name: "面值卡状态变动", title: "1", value: "CrmWeb/HYKGL/ZTBD/HYKGL_ZTBD_Srch.aspx?czk=1" },
     { id: 1143, pId: 114, name: "面值卡限门店设置", title: "zs", value: "CrmWeb/MZKGL/MZKXYMDSZ/MZKGL_MZKXYMDSZ.aspx" },
     { id: 1144, pId: 114, name: "面值卡操作台", title: "ys", value: "CrmWeb/MZKGL/MZKCZT/MZKGL_MZKCZT.aspx" },
   //  { id: 1145, pId: 114, name: "面值卡转储", title: "ys", value: "CrmWeb/MZKGL/MZKJEZC/MZKGL_MZKJEZC_Srch.aspx" },
     { id: 1146, pId: 114, name: "面值卡清零", title: "ys", value: "CrmWeb/MZKGL/MZKYEQL/MZKGL_MZKYEQL_Srch.aspx" },
     { id: 1146, pId: 114, name: "面值卡余额查询", title: "ys", value: "CrmWeb/MZKGL/MZKYECX/MZKGL_MZKYECX_Srch.aspx" },
     { id: 1146, pId: 114, name: "面值卡余额汇总", title: "ys", value: "CrmWeb/MZKGL/MZKYEHZ/MZKGL_MZKYEHZ_Srch.aspx" },

   //  { id: 1147, pId: 114, name: "顾客卡交易冲正处理", title: "ys", value: "CrmWeb/MZKGL/CZKCZCL/MZKGL_CZKCZCL_Srch.aspx" },
     { id: 1148, pId: 114, name: "面值卡并卡拆卡", title: "ys", value: "CrmWeb/MZKGL/MZKBKCK/MZKGL_MZKBKCK_Srch.aspx" },
   //  { id: 1149, pId: 114, name: "大客户 企业客户档案", title: "ys", value: "CrmWeb/MZKGL/DKHQYKHDA/MZKGL_DKHQYKHDA_Srch.aspx" },
   //  { id: 11410, pId: 114, name: "大客户 赊销合同", title: "ys", value: "CrmWeb/MZKGL/DKHSXHT/MZKGL_DKHSXHT_Srch.aspx" },
  //   { id: 11411, pId: 114, name: "大客户 赊销单", title: "ys", value: "CrmWeb/MZKGL/DKHSXD/MZKGL_DKHSXD_Srch.aspx" },
     { id: 11411, pId: 114, name: "面值卡每日充值金额限制", title: "ys", value: "CrmWeb/MZKGL/MZKMRCZXZ/MZKGL_MZKMRCZXZ_Srch.aspx" },
     { id: 11411, pId: 114, name: "面值卡支票启动", title: "ys", value: "CrmWeb/MZKGL/MZKZPQD/MZKGL_MZKZPQD_Srch.aspx" },
     { id: 11411, pId: 114, name: "面值卡回收查询", title: "ys", value: "CrmWeb/MZKGL/MZKHS/MZKGL_MZKHS_Srch.aspx" },
  //   { id: 11411, pId: 114, name: "面值卡赠送规则查询", title: "ys", value: "CrmWeb/MZKGL/MZKZSGZ/MZKGL_MZKZSGZ_Srch.aspx" },
     { id: 11416, pId: 114, name: "面值卡作废", title: "why", value: "CrmWeb/MZKGL/MZKZF/MZKGL_MZKZF_Srch.aspx" },
     //{ id: 11417, pId: 114, name: "面值卡消费查询", title: "why", value: "CrmWeb/MZKGL/MZKXFCX/MZKGL_MZKXFCX.aspx" },
     { id: 11418, pId: 114, name: "面值卡金额账处理记录", title: "why", value: "CrmWeb/HYKGL/HYKJEZHCLJL/HYKGL_HYKJEZHCLJL_Srch.aspx?czk=1" },
   //  { id: 11416, pId: 114, name: "面值卡售卡缴款单", title: "why", value: "CrmWeb/MZKGL/MZKSKJKD/MZKGL_SKJKD_Srch.aspx" },
   //  { id: 11416, pId: 114, name: "缴款单批量启动", title: "why", value: "CrmWeb/MZKGL/MZKPLQD_JKD/MZKGL_JKDPLQD_Srch.aspx" },
     //{ id: 11416, pId: 114, name: "面值卡金额账户处理记录查询", title: "why", value: "CrmWeb/HYKGL/HYKJEZHCLJL/HYKGL_HYKJEZHCLJL_Srch.aspx?czk=1" },
     { id: 11416, pId: 114, name: "库存面值卡查询", title: "zs", value: "CrmWeb/MZKGL/KCKCX/MZKGL_KCKCX_Srch.aspx" },
     { id: 11416, pId: 114, name: "库存面值卡保管帐", title: "zs", value: "CrmWeb/MZKGL/KCKBGZ/MZKGL_KCKBGZ_Srch.aspx" },
     { id: 11416, pId: 114, name: "库存面值卡报表", title: "zy", value: "CrmWeb/MZKGL/KCKBB/MZKGL_KCKBB_Srch.aspx" },
     { id: 11416, pId: 114, name: "库存卡金额调整", title: "zs", value: "CrmWeb/MZKGL/KCKYETZ/MZKGL_KCKYETZ_Srch.aspx" },

     { id: 11416, pId: 114, name: "库存卡作废", title: "zs", value: "CrmWeb/MZKGL/KCKZF/MZKGL_KCKZF_Srch.aspx?hf=0" },
     { id: 11416, pId: 114, name: "库存卡作废恢复", title: "zs", value: "CrmWeb/MZKGL/KCKZF/MZKGL_KCKZF_Srch.aspx?hf=1" },
     { id: 11416, pId: 114, name: "面值卡有效期延长", title: "1", value: "CrmWeb/MZKGL/YXQYC/MZKGL_YXQYC_Srch.aspx" },
     { id: 11416, pId: 114, name: "面值卡回收", title: "gx", value: "CrmWeb/MZKGL/MZKHS/MZKGL_MZKHS_Srch.aspx" },
     { id: 11416, pId: 114, name: "面值卡金额帐日报表", title: "gx", value: "CrmWeb/MZKGL/MZKJEZRBB/MZKGL_JEZRBB_Srch.aspx" },
     { id: 11416, pId: 114, name: "面值卡金额帐月报表", title: "gx", value: "CrmWeb/MZKGL/MZKJEZYBB/MZKGL_JEZYBB_Srch.aspx" },
     { id: 11416, pId: 114, name: "面值卡消费统计", title: "gx", value: "CrmWeb/MZKGL/MZKXFTJ/MZKGL_MZKXFTJ_Srch.aspx" },
     { id: 11416, pId: 114, name: "面值卡消费查询", title: "gx", value: "CrmWeb/MZKGL/MZKXFCX/MZKGL_MZKXFCX_Srch.aspx" },
     { id: 11416, pId: 114, name: "面值卡领取申请记录", title: "gx", value: "CrmWeb/MZKGL/MZK_LQSQJL/MZKGL_MZK_LQSQJL_Srch.aspx?czk=1&djlx=0" },
     { id: 11416, pId: 114, name: "面值卡交款单新", title: "gx", value: "CrmWeb/MZKGL/MZKJKDNEW/MZKGL_MZKJKDNEW_Srch.aspx" },
     { id: 11416, pId: 114, name: "面值卡盘点前处理", title: "gx", value: "CrmWeb/MZKGL/MZKPDQCL/MZKGL_MZKPDQCL_Srch.aspx?czk=1&djlx=0" },
     { id: 11416, pId: 114, name: "面值卡盘点录入", title: "gx", value: "CrmWeb/MZKGL/MZKPDLR/MZKGL_MZKPDLR_Srch.aspx?czk=1" },
     { id: 11416, pId: 114, name: "面值卡盘点汇总", title: "gx", value: "CrmWeb/MZKGL/MZKPDHZ/MZKGL_MZKPDHZ_Srch.aspx?czk=1" },
     { id: 11416, pId: 114, name: "面值卡盘点损益", title: "gx", value: "CrmWeb/MZKGL/MZKPDSY/MZKGL_MZKPDSY_Srch.aspx?czk=1" },
     { id: 11416, pId: 114, name: "面值卡按收款方式查询收款信息", title: "gx", value: "CrmWeb/MZKGL/MZKASKFSCXSKXX/MZKGL_MZKASKFSCXSKXX_Srch.aspx" },
     { id: 11416, pId: 114, name: "面值卡金额批量转储", title: "gx", value: "CrmWeb/MZKGL/MZKJEPLZC/MZKGL_MZKJEPLZC_Srch.aspx" },
     { id: 11416, pId: 114, name: "面值卡发售统计", title: "gx", value: "CrmWeb/MZKDKHGL/MZKFSTJ/MZKDKHGL_MZKFSTJ_Srch.aspx" },
     { id: 11416, pId: 114, name: "面值卡金额账报表", title: "gx", value: "CrmWeb/MZKGL/JEZBB/MZKGL_JEZBB_Srch.aspx" },
     { id: 11416, pId: 114, name: "面值卡金额定义", title: "gx", value: "CrmWeb/MZKGL/MZKJEDY/MZKGL_MZKJEDY.aspx" },
     { id: 11416, pId: 114, name: "面值卡售卡欠款查询", title: "gx", value: "CrmWeb/MZKGL/MZKSKQKCX/MZKGL_MZKSKQKCX_Srch.aspx" },
     { id: 11416, pId: 114, name: "按客户统计售卡汇总情况", title: "gx", value: "CrmWeb/MZKGL/AKHTJSKHZQK/MZKGL_AKHTJSKHZQK_Srch.aspx" },
     { id: 11416, pId: 114, name: "按商户统计面值卡消费", title: "gx", value: "CrmWeb/MZKGL/ASHTJMZKXF/MZKGL_ASHTJMZKXF.aspx" },
     { id: 11416, pId: 114, name: "按门店统计面值卡发售", title: "gx", value: "CrmWeb/MZKGL/AMDTJMZKFS/MZKGL_AMDTJMZKFS_Srch.aspx" },
     { id: 11416, pId: 114, name: "面值卡售卡赠券明细查询", title: "gx", value: "CrmWeb/MZKGL/MZKSKZQMXCX/MZKGL_MZKSKZQMXCX_Srch.aspx" },
     { id: 11416, pId: 114, name: "面值卡售卡赠分明细查询", title: "gx", value: "CrmWeb/MZKGL/MZKSKZFMXCX/MZKGL_MZKSKZFMXCX_Srch.aspx" },
     { id: 11416, pId: 114, name: "面值卡售卡卡号明细查询", title: "gx", value: "CrmWeb/MZKGL/MZKSKKHMXCX/MZKGL_MZKSKKHMXCX_Srch.aspx" },
     { id: 11416, pId: 114, name: "面值卡售卡管理员定义", title: "gx", value: "CrmWeb/MZKGL/SKGLYDY/MZKGL_SKGLYDY.aspx" },
     { id: 11416, pId: 114, name: "面值卡盘点汇总查询", title: "gx", value: "CrmWeb/MZKGL/MZKPDHZCX/MZKGL_MZKPDHZ_Srch.aspx" },
     { id: 11416, pId: 114, name: "面值卡缴款对账", title: "gx", value: "CrmWeb/MZKGL/MZKJKDZ/MZKGL_MZKJKDZ_Srch.aspx" },
     { id: 11416, pId: 114, name: "面值卡领用申请单", title: "zs", value: "CrmWeb/HYKGL/HYKLYSQ/HYKGL_HYKLYSQ_Srch.aspx?czk=1&djlx=0" },
     { id: 11416, pId: 114, name: "客户档案录入", title: "zs", value: "CrmWeb/MZKGL/KHDALR/MZKGL_KHDALR_Srch.aspx" },
     { id: 11416, pId: 114, name: "面值卡赠卡规则", title: "zs", value: "CrmWeb/MZKGL/CZKZKGZDY/MZKGL_CZKZKGZDY.aspx" },
     { id: 11416, pId: 114, name: "面值卡赠积分规则", title: "ys", value: "CrmWeb/MZKGL/CZKZJFGZDY/MZKGL_CZKZJFGZDY.aspx" },
     { id: 11416, pId: 114, name: "面值卡发售折现规则", title: "ys", value: "CrmWeb/MZKGL/CZKFSZXGZDY/MZKGL_CZKFSZXGZDY.aspx" },
     { id: 11416, pId: 114, name: "面值卡售卡单批量启动", title: "zs", value: "CrmWeb/MZKGL/MZKSKDPLQD/MZKGL_SKDPLQD_Srch.aspx" },
    { id: 11416, pId: 114, name: "面值卡发票处理", title: "zs", value: "CrmWeb/MZKGL/MZKKFP/MZKGL_MZKKFP.aspx" },
     { id: 11416, pId: 114, name: "面值卡存取款", title: "gx", value: "CrmWeb/MZKGL/MZKCQK/MZKGL_MZKCQK.aspx?action=add" },
     { id: 11416, pId: 114, name: "按收款方式统计面值卡存款情况", title: "gx", value: "CrmWeb/MZKGL/ASKFSTJMZKCQK/MZKGL_ASKFSTJMZKCQK.aspx" },


    { id: 115, pId: 11, name: "优惠券管理", title: "1" },
     //{ id: 1128, pId: 115, name: "积分抵现定义", title: "zs", value: "CrmWeb/YHQGL/JFDXGZ/YHQGL_JFDXGZ_Srch.aspx" },
     { id: 1128, pId: 115, name: "促销活动主题定义", title: "zs", value: "CrmWeb/YHQGL/CXHD/YHQGL_CXHDCX_Srch.aspx" },
     { id: 1154, pId: 115, name: "营销日历", title: "ys", value: "CrmWeb/YHQGL/YXRL/YHQGL_YXRL_Srch.aspx" },
     { id: 1128, pId: 115, name: "卡类型积分抵现比例定义", title: "zs", value: "CrmWeb/YHQGL/JFDXBL/YHQGL_JFDXBL_Srch.aspx" },
     { id: 1128, pId: 115, name: "促销积分抵现比例定义", title: "zs", value: "CrmWeb/YHQGL/CXJFDXBL/YHQGL_CXJFDXBL_Srch.aspx" },
     { id: 1128, pId: 115, name: "消费积分翻倍规则", title: "zs", value: "CrmWeb/YHQGL/JFBSGZ/YHQGL_JFBSGZ_Srch.aspx" },
     //满减1个规则2个单据
     { id: 1153, pId: 115, name: "满百减折规则定义", title: "ys", value: "CrmWeb/YHQGL/MBJZGZ/YHQGL_MBJZGZ_Srch.aspx" },
     { id: 1136, pId: 115, name: "促销满减定义单", title: "zy", value: "CrmWeb/HYXF/CXMBJZDYD/HYXF_CXMBJZDYD_Srch.aspx?mjjq=1" },
     { id: 1136, pId: 115, name: "促销满抵定义单", title: "zy", value: "CrmWeb/HYXF/CXMBJZDYD/HYXF_CXMBJZDYD_Srch.aspx?mjjq=0" },
     //用券1个规则2个单据
     { id: 1128, pId: 115, name: "优惠券使用规则", title: "zs", value: "CrmWeb/YHQGL/YHQSYGZ/YHQGL_YHQSYGZ_Srch.aspx" },
     { id: 1137, pId: 115, name: "优惠券使用定义单", title: "zy", value: "CrmWeb/HYXF/YQDYD/HYXF_YQDYD_Srch.aspx?djlx=0&lx=0" },
     { id: 1137, pId: 115, name: "积分抵现使用定义单", title: "zy", value: "CrmWeb/HYXF/YQDYD/HYXF_YQDYD_Srch.aspx?djlx=0&lx=5" },
     //发券4个规则11个单据，其中lx=3的规则可以被lx=3和4的单据选取（我就尼玛了，辣么多）
     { id: 1128, pId: 115, name: "优惠券发放规则", title: "zs", value: "CrmWeb/YHQGL/YHQFFGZ/YHQGL_YHQFFGZ_Srch.aspx?lx=0" },
     { id: 1128, pId: 115, name: "前台礼品发放规则", title: "zs", value: "CrmWeb/YHQGL/CJLPFFGZ/YHQGL_CJLPFFGZ_Srch.aspx?lx=1" },
     { id: 1128, pId: 115, name: "前台抽奖发放规则", title: "zs", value: "CrmWeb/YHQGL/CJFFGZ/YHQGL_CJFFGZ_Srch.aspx?lx=2" },
     { id: 1128, pId: 115, name: "消费送积分规则", title: "zs", value: "CrmWeb/YHQGL/SJFGZ/YHQGL_SJFGZ_Srch.aspx?lx=3" },

     { id: 1138, pId: 115, name: "优惠券发放定义单", title: "zy", value: "CrmWeb/HYXF/FQDYD/HYXF_FQDYD_Srch.aspx?djlx=0&lx=0" },
     { id: 1138, pId: 115, name: "促销礼品发放定义单", title: "zy", value: "CrmWeb/HYXF/FQDYD/HYXF_FQDYD_Srch.aspx?djlx=0&lx=1" },
     { id: 1138, pId: 115, name: "促销抽奖发放定义单", title: "zy", value: "CrmWeb/HYXF/FQDYD/HYXF_FQDYD_Srch.aspx?djlx=0&lx=2" },
     { id: 1138, pId: 115, name: "赠送积分定义单", title: "zy", value: "CrmWeb/HYXF/FQDYD/HYXF_FQDYD_Srch.aspx?djlx=0&lx=3" },
     { id: 1138, pId: 115, name: "促销积分定义单", title: "zy", value: "CrmWeb/HYXF/FQDYD/HYXF_FQDYD_Srch.aspx?djlx=0&lx=4" },

     { id: 1138, pId: 115, name: "优惠券发放定义单支付送", title: "zy", value: "CrmWeb/HYXF/FQDYD/HYXF_FQDYD_Srch.aspx?djlx=2&lx=0" },
     { id: 1138, pId: 115, name: "促销礼品发放定义单支付送", title: "zy", value: "CrmWeb/HYXF/FQDYD/HYXF_FQDYD_Srch.aspx?djlx=2&lx=1" },
     { id: 1138, pId: 115, name: "促销抽奖发放定义单支付送", title: "zy", value: "CrmWeb/HYXF/FQDYD/HYXF_FQDYD_Srch.aspx?djlx=2&lx=2" },
     { id: 1138, pId: 115, name: "赠送积分定义单支付送", title: "zy", value: "CrmWeb/HYXF/FQDYD/HYXF_FQDYD_Srch.aspx?djlx=2&lx=3" },
     { id: 1138, pId: 115, name: "促销积分定义单支付送", title: "zy", value: "CrmWeb/HYXF/FQDYD/HYXF_FQDYD_Srch.aspx?djlx=2&lx=4" },

     { id: 1138, pId: 115, name: "赠送积分定义单首刷礼", title: "zy", value: "CrmWeb/HYXF/FQDYD/HYXF_FQDYD_Srch.aspx?djlx=3&lx=3" },

     { id: 1151, pId: 115, name: "来店赠券活动定义", title: "ys", value: "CrmWeb/YHQGL/LDZQ/YHQGL_LDZQHDDY.aspx" },
     { id: 1152, pId: 115, name: "来店赠券规则", title: "ys", value: "CrmWeb/YHQGL/LDZQ/YHQGL_LDZQGZ_Srch.aspx" },
     { id: 1153, pId: 115, name: "来店赠券", title: "ys", value: "CrmWeb/YHQGL/LDZQ/YHQGL_LDZQ_Srch.aspx" },
     { id: 1153, pId: 115, name: "优惠券面值定义", title: "ys", value: "CrmWeb/YHQGL/MZDY/YHQGL_MZDY_Srch.aspx" },
     { id: 1153, pId: 115, name: "优惠券账户当前余额查询", title: "ys", value: "CrmWeb/YHQGL/YHQDQYE/YHQGL_YHQDQYE_Srch.aspx" },
     { id: 1153, pId: 115, name: "按合同汇总收发券记录查询", title: "ys", value: "CrmWeb/YHQGL/HTSFQJLHZ/YHQGL_HTSFQJLHZ_Srch.aspx" },
     { id: 1153, pId: 115, name: "按部门汇总收发券记录查询", title: "ys", value: "CrmWeb/YHQGL/BMSFQJLHZ/YHQGL_BMSFQJLHZ_Srch.aspx" },
     { id: 1153, pId: 115, name: "按商品汇总收发券记录查询", title: "ys", value: "CrmWeb/YHQGL/SPSFQJLHZ/YHQGL_SPSFQJLHZ_Srch.aspx" },
     { id: 1153, pId: 115, name: "按商品分类汇总收发券记录查询", title: "ys", value: "CrmWeb/YHQGL/SPFLSFQJLHZ/YHQGL_SPFLSFQJLHZ_Srch.aspx" },
     { id: 1153, pId: 115, name: "按商品查询促销活动", title: "ys", value: "CrmWeb/YHQGL/SPCXHD/YHQGL_SPCXHD_Srch.aspx" },
     { id: 1153, pId: 115, name: "按商品查询基础积分", title: "ys", value: "CrmWeb/YHQGL/SPCXHD/YHQGL_SPCXHD_Srch.aspx?lx=1" },
     { id: 1153, pId: 115, name: "按商品查询折扣", title: "ys", value: "CrmWeb/YHQGL/SPCXHD/YHQGL_SPCXHD_Srch.aspx?lx=2" },
     { id: 1153, pId: 115, name: "按商品查询返券", title: "ys", value: "CrmWeb/YHQGL/SPCXHD/YHQGL_SPCXHD_Srch.aspx?lx=3" },
     { id: 1153, pId: 115, name: "按商品查询用券", title: "ys", value: "CrmWeb/YHQGL/SPCXHD/YHQGL_SPCXHD_Srch.aspx?lx=4" },
     { id: 1154, pId: 115, name: "优惠券预存增值", title: "ys", value: "CrmWeb/YHQGL/YHQCKGZ/YHQGL_YHQCKGZ_Srch.aspx" },
     { id: 1154, pId: 115, name: "前台积分抵现记录查询", title: "ys", value: "CrmWeb/YHQGL/QTJFDHJL/YHQGL_QTJFDHJL_Srch.aspx" },
     { id: 1154, pId: 115, name: "待发券记录信息查询", title: "ys", value: "CrmWeb/YHQGL/DFQJLXXCX/YHQGL_DFQJLXXCX.aspx" },
      { id: 1154, pId: 115, name: "待发券记录汇总查询", title: "ys", value: "CrmWeb/YHQGL/DFQJLXXHZCX/YHQGL_DFQJLXXHZCX.aspx" },
     { id: 1154, pId: 115, name: "金额帐记录转储记录查询", title: "ys", value: "CrmWeb/YHQGL/JEZCL/YHQGL_JEZJEZCJLCX.aspx" },
     { id: 1154, pId: 115, name: "收券记录汇总查询", title: "ys", value: "CrmWeb/YHQGL/YQJLHZXX/YHQGL_SQJLHZXX_Srch.aspx" },
     { id: 1154, pId: 115, name: "优惠券促销分析", title: "ys", value: "CrmWeb/YHQGL/YHQCXFX/YHQGL_YHQCXFX_Srch.aspx" },

    { id: 117, pId: 11, name: "导航图", title: "1" },
      { id: 1102, pId: 117, name: "促销导航图", title: "ys", value: "CrmWeb/CRMGL/CRMDHT/DHT_CXDHT.aspx" },
      { id: 1102, pId: 117, name: "抽奖促销", title: "ys", value: "CrmWeb/CRMGL/CRMDHT/DHT_CJ.aspx" },
      { id: 1102, pId: 117, name: "促销满抵", title: "ys", value: "CrmWeb/CRMGL/CRMDHT/DHT_MD.aspx" },
      { id: 1102, pId: 117, name: "促销满减", title: "ys", value: "CrmWeb/CRMGL/CRMDHT/DHT_MJ.aspx" },
      { id: 1102, pId: 117, name: "会员折扣导航图", title: "ys", value: "CrmWeb/CRMGL/CRMDHT/DHT_ZK.aspx" },
      { id: 1102, pId: 117, name: "积分导航图", title: "ys", value: "CrmWeb/CRMGL/CRMDHT/DHT_JF.aspx" },
      { id: 1102, pId: 117, name: "客群组导航图", title: "ys", value: "CrmWeb/CRMGL/CRMDHT/DHT_HYZ.aspx" },
      { id: 1102, pId: 117, name: "礼品导航图", title: "ys", value: "CrmWeb/CRMGL/CRMDHT/DHT_LP.aspx" },
      { id: 1102, pId: 117, name: "优惠券导航图", title: "ys", value: "CrmWeb/CRMGL/CRMDHT/DHT_YHQ.aspx" },

    { id: 118, pId: 11, name: "大客户管理", title: "1" },
    { id: 1129, pId: 118, name: "大客户等级定义", title: "ys", value: "CrmWeb/MZKDKHGL/DKHDJDY/MZKDKHGL_DKHDJDY.aspx" },
    { id: 1129, pId: 118, name: "大客户支付方式定义", title: "ys", value: "CrmWeb/MZKDKHGL/ZFFSDY/MZKDKHGL_ZFFSDY.aspx" },
    { id: 1129, pId: 118, name: "大客户赊销还款单查询", title: "ys", value: "CrmWeb/MZKDKHGL/DKHSXFK/MZKDKHGL_SXFK_Srch.aspx" },
    { id: 1129, pId: 118, name: "大客户资料录入", title: "ys", value: "CrmWeb/MZKDKHGL/GRDKHZLLR/MZKDKHGL_DKHZLLR_Srch.aspx" },
    { id: 1129, pId: 118, name: "客服专员变更记录", title: "ys", value: "CrmWeb/MZKDKHGL/KFZYBGJL/MZKDKHGL_KFZYBGJL_Srch.aspx" },
    { id: 1129, pId: 118, name: "关联代办员与会员查询", title: "ys", value: "CrmWeb/MZKDKHGL/GLHYYDBY/MZKDKHGL_GLGYYDBY_Srch.aspx" },
    { id: 1129, pId: 118, name: "代办员资料修改", title: "ys", value: "CrmWeb/MZKDKHGL/DBYZLXG/MZKDKHGL_DBYZLXG.aspx" },
    { id: 1129, pId: 118, name: "储值卡赠卡规则", title: "ys", value: "CrmWeb/MZKDKHGL/CZKZKGZ/MZKDKHGL_CZKZKGZ.aspx" },
    { id: 1129, pId: 118, name: "储值卡赠礼品规则", title: "ys", value: "CrmWeb/MZKDKHGL/CZKZLPGZ/MZKDKHGL_CZKZLPGZ.aspx" },
    { id: 1129, pId: 118, name: "大客户专员定义", title: "ys", value: "CrmWeb/MZKDKHGL/DKHZYDY/MZKDKHGL_DKHZYDY.aspx" },
    { id: 1129, pId: 118, name: "大客户售卡积分设置 ", title: "ys", value: "CrmWeb/MZKDKHGL/DKHJFSZ/MZKDKHGL_DKHJFSZ.aspx" },
    { id: 1129, pId: 118, name: "企业代办员管理 ", title: "ys", value: "CrmWeb/MZKDKHGL/QYDBYGL/MZKDKHGL_QYDBYGL.aspx" },
    { id: 1129, pId: 118, name: "企业大客户资料导入 ", title: "ys", value: "CrmWeb/MZKDKHGL/QYDKHZLDR/MZKDKHGL_QYDKHZLDR_Srch.aspx" },
    { id: 1129, pId: 118, name: "大客户售卡单修改客户资料 ", title: "ys", value: "CrmWeb/MZKDKHGL/SKDXGKHZL/MZKDKHGL_SKDXGKHZL_Srch.aspx" },

    { id: 120, pId: 11, name: "CRM报表", title: "1" },
    { id: 1101, pId: 120, name: "新增会员分析", title: "ys", value: "CrmWeb/CRMREPORT/XZHYSL/CRMREPORT_XZHYSL.aspx" },
    { id: 1101, pId: 120, name: "线上用户活跃趋势", title: "ys", value: "CrmWeb/CRMREPORT/XSYHHYQS/CRMREPORT_XSYHHYQS.aspx" },
    { id: 1101, pId: 120, name: "用户画像", title: "ys", value: "CrmWeb/CRMREPORT/YHHX/CRMREPORT_YHHX.aspx" },
    { id: 1101, pId: 120, name: "手机终端分析", title: "ys", value: "CrmWeb/CRMREPORT/SJZDFX/CRMREPORT_SJZDFX.aspx" },
    //{ id: 1101, pId: 120, name: "RFM级别定义", title: "ys", value: "CrmWeb/CRMREPORT/RFMJBDY/CRMREPORT_RFMJBDY.aspx" },
    // //{ id: 1101, pId: 120, name: "RFM分析指标定义", title: "ys", value: "CrmWeb/CRMREPORT/RFMFXZB/CRMREPORT_RFMFXZB.aspx" },
    // //{ id: 1101, pId: 120, name: "门店RFM分析指标定义", title: "ys", value: "CrmWeb/CRMREPORT/RFMFXZBMD/CRMREPORT_RFMFXZBMD.aspx" },

    // { id: 1104, pId: 120, name: "BMF权重定义", title: "ys", value: "CrmWeb/CRMREPORT/BFMZQDY/CRMREPORT_BFMZQDY.aspx" },
    // { id: 1137, pId: 120, name: "RFM分析指标定义", title: "zs", value: "CrmWeb/CRMREPORT/RFMFXZB/CRMREPORT_RFMFXZB.aspx?LX=1" },
    // { id: 1137, pId: 120, name: "门店RFM分析指标定义", title: "zs", value: "CrmWeb/CRMREPORT/RFMFXZB/CRMREPORT_RFMFXZB.aspx?LX=2" },
    //         { id: 1166, pId: 120, name: "会员消费分析", title: "zs", value: "CrmWeb/CRMREPORT/HYXFFX/CRMREPORT_HYXFFX.aspx" },
    //    { id: 1166, pId: 120, name: "重复购买率分析", value: "CrmWeb/CRMREPORT/CFGML/CRMREPORT_CFGML.aspx" },
    //    { id: 1166, pId: 120, name: "会员结构分析", value: "CrmWeb/CRMREPORT/HYJG/CRMREPORT_HYJG.aspx" },
    //    { id: 1166, pId: 120, name: "会员客单价分析", value: "CrmWeb/CRMREPORT/HYKDJ/CRMREPORT_HYKDJ.aspx" },
    //    { id: 1166, pId: 120, name: "RFM价值分析", value: "CrmWeb/CRMREPORT/RFMJZFX/CRMREPORT_RFMJZFX.aspx" },
    //    { id: 1166, pId: 120, name: "RFM品类分析", value: "CrmWeb/CRMREPORT/RFMJZFX/CRMREPORT_RFMPLFX.aspx" },
    //    { id: 1166, pId: 120, name: "RFM稳定性分析", value: "CrmWeb/CRMREPORT/WDXFX/CRMREPORT_WDXFX.aspx" },
    //    { id: 1166, pId: 120, name: "按部门品牌查询积分", value: "CrmWeb/CRMREPORT/BMFLJF/CRMREPORT_BMFLJF.aspx" },
    //    { id: 1166, pId: 120, name: "RFM偏好分析", value: "CrmWeb/CRMREPORT/RFMPHFX/CRMREPORT_RFMPHFX.aspx" },
    //    { id: 1166, pId: 120, name: "活跃度分析", value: "CrmWeb/CRMREPORT/HYDFX/CRMREPORT_HYDFX.aspx" },
    //    { id: 1166, pId: 120, name: "流失率分析", value: "CrmWeb/CRMREPORT/HYLSL/CRMREPORT_HYLSL.aspx" },
    //    { id: 1166, pId: 120, name: "新增会员消费分析", value: "CrmWeb/CRMREPORT/XZHYXFFX/CRMREPORT_XZHYXFFX.aspx" },
    //    { id: 1166, pId: 120, name: "会员分卡种客单价分析", value: "CrmWeb/CRMREPORT/HYFKZKDJ/CRMREPORT_HYFKZKDJ.aspx" },
    //    { id: 1166, pId: 120, name: "客户群分析", value: "CrmWeb/CRMREPORT/KQ_KQZFX/CRMREPORT_KQ_KQZFX.aspx" },
    //    { id: 1166, pId: 120, name: "客户群静态属性分析", value: "CrmWeb/CRMREPORT/KQ_JTSXFX/CRMREPORT_KQ_JTSXFX.aspx" },
    //    { id: 1166, pId: 120, name: "客户群消费趋势分析", value: "CrmWeb/CRMREPORT/KQ_XFQSFX/CRMREPORT_KQ_XFQSFX.aspx" },
    //    { id: 1166, pId: 120, name: "客户群消费品类分析", value: "CrmWeb/CRMREPORT/KQ_XFPLFX/CRMREPORT_KQ_XFPLFX.aspx" },
    //    { id: 1166, pId: 120, name: "客户群消费偏好分析", value: "CrmWeb/CRMREPORT/KQ_XFPHFX/CRMREPORT_KQ_XFPHFX.aspx" },
    //    { id: 1166, pId: 120, name: "客户群客单价分析", value: "CrmWeb/CRMREPORT/KQ_DJFX/CRMREPORT_KQ_DJFX.aspx" },
    //    { id: 1166, pId: 120, name: "会员等级消费日报表", value: "CrmWeb/CRMREPORT/HYDJXFRBB/CRMREPORT_HYDJXFRBB.aspx" },
    //    { id: 1166, pId: 120, name: "会员分类消费日报表", value: "CrmWeb/CRMREPORT/HYFLXFRBB/CRMREPORT_HYFLXFRBB.aspx" },
    //    { id: 1166, pId: 120, name: "会员消费日报表", value: "CrmWeb/CRMREPORT/HYXFRBB/CRMREPORT_HYXFRBB.aspx" },
    //    { id: 1166, pId: 120, name: "会员生命周期分析", value: "CrmWeb/CRMREPORT/HYSMZQFX/CRMREPORT_HYSMZQFX.aspx" },
    //    { id: 1166, pId: 120, name: "按门店分析消费星期习惯（月）", value: "CrmWeb/CRMREPORT/HYXFXQXG/CRMREPORT_HYXFXQXG.aspx" },
    //    { id: 1166, pId: 120, name: "按门店分析消费时段习惯", value: "CrmWeb/CRMREPORT/HYXFSDXG/CRMREPORT_HYXFSDXG.aspx" },
    //    { id: 1166, pId: 120, name: "按客群分析消费时段习惯", value: "CrmWeb/CRMREPORT/KQ_HYXFSDXG/CRMREPORT_KQ_HYXFSDXG.aspx" },
    //    { id: 1166, pId: 120, name: "按客群分析消费星期习惯", value: "CrmWeb/CRMREPORT/KQ_HYXFXQXG/CRMREPORT_KQ_HYXFXQXG.aspx" },
    //    { id: 1166, pId: 120, name: "门店价格带消费分析", value: "CrmWeb/CRMREPORT/HYJGDFX/CRMREPORT_HYJGDFX.aspx" },
    //    { id: 1166, pId: 120, name: "会员价值分析（月）", value: "CrmWeb/CRMREPORT/HYJZFX/CRMREPORT_HYJZFX.aspx" },
    //    { id: 1166, pId: 120, name: "会员节假日分析（年）", value: "CrmWeb/CRMREPORT/HYJJRFX/CRMREPORT_HYJJRFX.aspx" },
    //    { id: 1166, pId: 120, name: "会员营销活动分析（年）", value: "CrmWeb/CRMREPORT/HYYXHDFX/CRMREPORT_HYYXHDFX.aspx" },
    //    { id: 1166, pId: 120, name: "会员积分返利分析报表", value: "CrmWeb/CRMREPORT/HYJFFLFX/CRMREPORT_HYJFFLFX.aspx" },
    //    { id: 1166, pId: 120, name: "节假日日期定义", value: "CrmWeb/CRMREPORT/JJR_RQ_DEF/CRMREPORT_JJR_RQ_DEF.aspx" },
    //    { id: 1166, pId: 120, name: "营销活动定义", value: "CrmWeb/CRMREPORT/YXHDEF/CRMREPORT_YXHDDEF_Srch.aspx" },
    //    { id: 1166, pId: 120, name: "节假日定义", value: "CrmWeb/CRMREPORT/JJRDEF/CRMREPORT_JJRDEF.aspx" },
    //    { id: 1166, pId: 120, name: "商圈小区消费分析", value: "CrmWeb/CRMREPORT/SQXQXFFX/CRMREPORT_SQXQXFFX.aspx" },
    //    { id: 1166, pId: 120, name: "新增会员日期分析", value: "CrmWeb/CRMREPORT/XZHYRQFX/CRMREPORT_XZHYRQFX.aspx" },
    //    { id: 1166, pId: 120, name: "会员价商品销售查询", value: "CrmWeb/CRMREPORT/HYZXSPXSCX/CRMREPORT_HYZXSPXSCX.aspx?HYZX=0" },
    //    { id: 1166, pId: 120, name: "会员专享商品销售查询", value: "CrmWeb/CRMREPORT/HYZXSPXSCX/CRMREPORT_HYZXSPXSCX.aspx?HYZX=1" },
    //    { id: 1166, pId: 120, name: "商圈小区分析", value: "CrmWeb/CRMREPORT/SQXQFX/CRMREPORT_SQXQFX.aspx" },
    //    { id: 1166, pId: 120, name: "会员卡状态分析", value: "CrmWeb/CRMREPORT/HYZTFX/CRMREPORT_HYZTFX.aspx" },

      { id: 121, pId: 11, name: "客服平台", title: "1" },
      { id: 1102, pId: 121, name: "促销信息", title: "ys", value: "CrmWeb/KFPT/CXXX/KFPT_CXXX_Srch.aspx" },
      { id: 1102, pId: 121, name: "会员日消费预警", title: "ys", value: "CrmWeb/KFPT/XFYJ/KFPT_XFYJ.aspx" },
      { id: 1102, pId: 121, name: "客户消费等级组定义", title: "ys", value: "CrmWeb/KFPT/KHXFDJZDY/KFPT_KHXFDJZDY.aspx" },
       { id: 1102, pId: 121, name: "会员信用等级组定义", title: "ys", value: "CrmWeb/KFPT/HYXYDJZDY/KFPT_HYXYDJZDY.aspx" },
       { id: 1102, pId: 121, name: "当日消费金额预警", title: "ys", value: "CrmWeb/KFPT/DRXFJEYJDY/KFPT_DRXFJEYJDY_Srch.aspx" },
        { id: 1102, pId: 121, name: "会员升级预警", title: "ys", value: "CrmWeb/KFPT/HYSJYJ/KFPT_HYSJYJ.aspx" },
        { id: 1102, pId: 121, name: "一日工作安排", title: "ys", value: "CrmWeb/KFPT/YRGZAP/KFPT_YRGZAP.aspx" },
      { id: 1102, pId: 121, name: "单一会员分析", title: "ys", value: "CrmWeb/KFPT/DYHYFX/KFPT_DYHYFX.aspx" },
       { id: 1102, pId: 121, name: "部门会员消费分析", title: "ys", value: "CrmWeb/KFPT/BMHYXFFX/KFPT_BMHYXFFX_Srch.aspx" },
        { id: 1102, pId: 121, name: "工作量统计", title: "ys", value: "CrmWeb/KFPT/GZLTJ/KFPT_GZLTJ_Srch.aspx" },
        { id: 1102, pId: 121, name: "客服组定义", title: "ys", value: "CrmWeb/KFPT/KFZDY/KFPT_KFZDY_Srch.aspx" },
        { id: 1102, pId: 121, name: "会员客户经理定义", title: "ys", value: "CrmWeb/KFPT/KFJLDY/KFPT_KFJLDY_Srch.aspx" },
        { id: 1102, pId: 121, name: "会员客户经理修改", title: "ys", value: "CrmWeb/KFPT/KFJLXG/KFPT_KFJLXG_Srch.aspx" },
        { id: 1102, pId: 121, name: "客户经理会员查询", title: "ys", value: "CrmWeb/KFPT/KFJLHYCX/KFPT_KFJLHYCX_Srch.aspx" },
        { id: 1102, pId: 121, name: "会员活动定义", title: "ys", value: "CrmWeb/KFPT/HYHDDY/KFPT_HYHDDY_Srch.aspx" },
        { id: 1102, pId: 121, name: "会员活动报名", title: "ys", value: "CrmWeb/KFPT/HYHDBM/KFPT_HYHDBM_Srch.aspx" },
        { id: 1102, pId: 121, name: "会员活动参加", title: "ys", value: "CrmWeb/KFPT/HYHDCJ/KFPT_HYHDCJ_Srch.aspx" },
        { id: 1102, pId: 121, name: "会员活动回访", title: "ys", value: "CrmWeb/KFPT/HYHDHF/KFPT_HYHDHF_Srch.aspx" },
        { id: 1102, pId: 121, name: "会员活动领导评述", title: "ys", value: "CrmWeb/KFPT/HYHDLDPS/KFPT_HYHDLDPS_Srch.aspx" },
        { id: 1102, pId: 121, name: "活动分析", title: "ys", value: "CrmWeb/KFPT/HDFX/KFPT_HDFX_Srch.aspx" },
        { id: 1102, pId: 121, name: "任务发布", title: "ys", value: "CrmWeb/KFPT/RWFB/KFPT_RWFB_Srch.aspx" },
        { id: 1102, pId: 121, name: "任务执行", title: "ys", value: "CrmWeb/KFPT/RWZX/KFPT_RWZX_Srch.aspx" },
        { id: 1102, pId: 121, name: "任务处理", title: "ys", value: "CrmWeb/KFPT/RWCL/KFPT_RWCL_Srch.aspx" },
        { id: 1102, pId: 121, name: "查询已执行任务", title: "ys", value: "CrmWeb/KFPT/CXYZXRW/KFPT_CXYZXRW_Srch.aspx" },
        { id: 1102, pId: 121, name: "群体会员喜好品牌", title: "ys", value: "CrmWeb/KFPT/QTHYXHSB/KFPT_QTHYXHSB_Srch.aspx" },
        { id: 1102, pId: 121, name: "会员消费同、环比分析", title: "ys", value: "CrmWeb/KFPT/HYXFTQB/KFPT_HYXFTQB_Srch.aspx" },
        { id: 1102, pId: 121, name: "客户消费等级组分析", title: "ys", value: "CrmWeb/KFPT/KHXFDJZFX/KFPT_KHXFDJZFX_Srch.aspx" },
        { id: 1102, pId: 121, name: "会员生日电话检查", title: "ys", value: "CrmWeb/KFPT/HYSRDHJC/KFPT_HYSRDHJC_Srch.aspx" },
        { id: 1102, pId: 121, name: "生日会员", title: "ys", value: "CrmWeb/KFPT/SRHY/KFPT_SRHY.aspx" },
        { id: 1102, pId: 121, name: "定期会员电话维护", title: "ys", value: "CrmWeb/KFPT/DQHYDHWH/KFPT_DQHYDHWH_Srch.aspx" },
        { id: 1102, pId: 121, name: "未消费会员电话维护", title: "ys", value: "CrmWeb/KFPT/WXFHYDHWH/KFPT_WXFHYDHWH.aspx" },
        { id: 1102, pId: 121, name: "电话维护记录查询", title: "ys", value: "CrmWeb/KFPT/DHWHJLCX/KFPT_DHWHJLCX.aspx" },
        { id: 1102, pId: 121, name: "客服人员填写备注信息查询", title: "ys", value: "CrmWeb/KFPT/VIPBZXXCX/KFPT_VIPBZXXCX_Srch.aspx" },
     { id: 1102, pId: 121, name: "投诉记录", title: "ys", value: "CrmWeb/KFPT/TSJL/KFPT_TSJL_Srch.aspx" },


       { id: 122, pId: 11, name: "监控平台", title: "1" },
      { id: 1102, pId: 122, name: "预警会员日数据", title: "ys", value: "CrmWeb/JKPT/YJHYR/JKPT_YJHYR_Srch.aspx?zb=0" },
      { id: 1102, pId: 122, name: "预警会员月数据", title: "ys", value: "CrmWeb/JKPT/YJHYY/JKPT_YJHYY_Srch.aspx?zb=0" },
      { id: 1102, pId: 122, name: "门店消费次数监控日", title: "ys", value: "CrmWeb/JKPT/MDXFCSJKR/JKPT_MDXFCSJKR_Srch.aspx" },
      { id: 1102, pId: 122, name: "门店消费次数监控月", title: "ys", value: "CrmWeb/JKPT/MDXFCSJKY/JKPT_MDXFCSJKY_Srch.aspx" },

      { id: 1102, pId: 122, name: "收款台消费次数监控日", title: "ys", value: "CrmWeb/JKPT/SKTXFCSJKR/JKPT_SKTXFCSJKR_Srch.aspx" },
      { id: 1102, pId: 122, name: "单收款台消费次数监控日", title: "ys", value: "CrmWeb/JKPT/DSKTXFCSJKR/JKPT_DSKTXFCSJKR_Srch.aspx" },
      { id: 1102, pId: 122, name: "收款台消费次数监控月", title: "ys", value: "CrmWeb/JKPT/SKTXFCSJKY/JKPT_SKTXFCSJKY_Srch.aspx" },
      { id: 1102, pId: 122, name: "单收款台消费次数监控月", title: "ys", value: "CrmWeb/JKPT/DSKTXFCSJKY/JKPT_DSKTXFCSJKY_Srch.aspx" },

      { id: 1102, pId: 122, name: "部门消费次数监控日", title: "ys", value: "CrmWeb/JKPT/BMXFCSJKR/JKPT_BMXFCSJKR_Srch.aspx" },
      { id: 1102, pId: 122, name: "单部门消费次数监控日", title: "ys", value: "CrmWeb/JKPT/DBMXFCSJKR/JKPT_DBMXFCSJKR_Srch.aspx" },
      { id: 1102, pId: 122, name: "部门消费次数监控月", title: "ys", value: "CrmWeb/JKPT/BMXFCSJKY/JKPT_BMXFCSJKY_Srch.aspx" },
      { id: 1102, pId: 122, name: "单部门消费次数监控月", title: "ys", value: "CrmWeb/JKPT/DBMXFCSJKY/JKPT_DBMXFCSJKY_Srch.aspx" },

      { id: 1102, pId: 122, name: "会员门店消费日排名", title: "ys", value: "CrmWeb/JKPT/MDPMR/JKPT_MDPMR_Srch.aspx" },
      { id: 1102, pId: 122, name: "会员门店消费月排名", title: "ys", value: "CrmWeb/JKPT/MDPMY/JKPT_MDPMY_Srch.aspx" },
      { id: 1102, pId: 122, name: "会员收款台消费日排名", title: "ys", value: "CrmWeb/JKPT/SKTPMR/JKPT_SKTPMR_Srch.aspx" },
      { id: 1102, pId: 122, name: "会员收款台消费月排名", title: "ys", value: "CrmWeb/JKPT/SKTPMY/JKPT_SKTPMY_Srch.aspx" },
      { id: 1102, pId: 122, name: "会员部门消费排名日", title: "ys", value: "CrmWeb/JKPT/BMXFPMR/JKPT_BMXFPMR_Srch.aspx" },
      { id: 1102, pId: 122, name: "会员部门消费排名月", title: "ys", value: "CrmWeb/JKPT/BMXFPMY/JKPT_BMXFPMY_Srch.aspx" },

      { id: 1102, pId: 122, name: "可疑会员", title: "ys", value: "CrmWeb/JKPT/KYHY/JKPT_KYHY_Srch.aspx" },
      { id: 1102, pId: 122, name: "预警规则定义", title: "ys", value: "CrmWeb/JKPT/YJGZDEF/JKPT_YJGZDEF_Srch.aspx" },

          { id: 123, pId: 11, name: "移动端管理系统", title: "1" },
      { id: 1201, pId: 123, name: "移动端品牌介绍", title: "", value: "CrmWeb/APP/YDDPPJS/APP_YDDPPJS_Srch.aspx" },
      { id: 1201, pId: 123, name: "移动端生活服务类介绍", title: "", value: "CrmWeb/APP/SHFULJS/APP_SHFWLJS_Srch.aspx" },
      { id: 1201, pId: 123, name: "移动端预约服务定义", title: "", value: "CrmWeb/APP/YDDYYFWDY/APP_YDDYYFWDY_Srch.aspx" },
      { id: 1201, pId: 123, name: "移动端调查题目定义", title: "", value: "CrmWeb/APP/YDDDCTMDY/APP_YDDDCTMDY_Srch.aspx" },
      { id: 1201, pId: 123, name: "移动端调查定义单", title: "", value: "CrmWeb/APP/YDDDCDYD/APP_YDDDCDYD_Srch.aspx" },
      { id: 1201, pId: 123, name: "移动端开卡赠送积分规则定义", title: "", value: "CrmWeb/APP/YDDKKSLP/APP_YDDKKSLP_Srch.aspx?gzlx=1" },
      { id: 1201, pId: 123, name: "移动端绑卡赠送积分规则定义", title: "", value: "CrmWeb/APP/YDDKKSLP/APP_YDDKKSLP_Srch.aspx?gzlx=2" },
      { id: 1201, pId: 123, name: "移动端签到赠送积分规则定义", title: "", value: "CrmWeb/APP/YDDQDSJFDY/APP_YDDQDSJFDY_Srch.aspx" },
      { id: 1201, pId: 123, name: "移动端大分类定义", title: "", value: "CrmWeb/APP/YDDDXFLDY/APP_YDDDXFLDY_Srch.aspx" },
      { id: 1201, pId: 123, name: "移动端小分类定义", title: "", value: "CrmWeb/APP/YDDXFLDY/APP_YDDXFXDY_Srch.aspx" },
      { id: 1201, pId: 123, name: "移动端贴心服务定义", title: "", value: "CrmWeb/APP/TXFWDY/APP_TXFWDY_Srch.aspx" },
      { id: 1201, pId: 123, name: "移动端礼品组包定义", title: "", value: "CrmWeb/APP/LPZBDY/APP_LPZBDY_Srch.aspx" },
      { id: 1201, pId: 123, name: "移动端最新活动定义", title: "", value: "CrmWeb/APP/YDDZXHDLXDY/APP_YDDZXHDLXDY_Srch.aspx" },
      { id: 1201, pId: 123, name: "移动端最新活动门店定义", title: "", value: "CrmWeb/APP/YDDZXHDMDDY/APP_YDDZXHDMDDY.aspx" },
     { id: 1201, pId: 123, name: "移动端游戏奖品级次定义", title: "", value: "CrmWeb/APP/YDDYXJPJCDY/APP_YDDYXJPJCDY.aspx" },
     { id: 1201, pId: 123, name: "移动端商户定义", title: "", value: "CrmWeb/APP/SHDY/APP_SHDY.aspx" },
     { id: 1201, pId: 123, name: "移动端区域定义", title: "", value: "CrmWeb/APP/QYDY/APP_QYDY.aspx" },
     { id: 1201, pId: 123, name: "移动端礼品发放规则定义", title: "", value: "CrmWeb/APP/LPFFGZDY/APP_LPFFGZDY_Srch.aspx" },
     { id: 1201, pId: 123, name: "移动端业态门店定义", title: "", value: "CrmWeb/APP/YTMDDY/APP_YTMDDY_Srch.aspx" },
     { id: 1201, pId: 123, name: "移动端品牌推荐", title: "", value: "CrmWeb/APP/YDDPPTJ/APP_YDDPPTJ_Srch.aspx" },
     { id: 1201, pId: 123, name: "移动端会员权益定义", title: "", value: "CrmWeb/APP/HYQYDY/APP_HYQYDY_Srch.aspx" },
     { id: 1201, pId: 123, name: "移动端投诉类型定义", title: "", value: "CrmWeb/APP/TSLXDY/APP_TSLXDY.aspx" },
     { id: 1201, pId: 123, name: "移动端商品推荐", title: "", value: "CrmWeb/GTPT/WXSPTJDY/GTPT_WXSPTJDY_Srch.aspx" },
     { id: 1201, pId: 123, name: "移动端联盟商户类型定义", title: "", value: "CrmWeb/APP/LMSHLXDY/APP_LMSHLXDY_Srch.aspx" },
     { id: 1201, pId: 123, name: "移动端联盟商户定义", title: "", value: "CrmWeb/APP/LMSHDY/APP_LMSHDY_Srch.aspx" },
     { id: 1201, pId: 123, name: "移动端门店楼层品牌商标定义", title: "", value: "CrmWeb/APP/MDLCSBDY/APP_MDLCSBDY_Srch.aspx" },
     { id: 1201, pId: 123, name: "移动端门店楼层定义", title: "", value: "CrmWeb/APP/MDLCDY/APP_MDLCDY_Srch.aspx" },
     { id: 1201, pId: 123, name: "移动端餐厅类型定义", title: "", value: "CrmWeb/APP/CTLXDY/APP_CTLXDY_Srch.aspx" },
     { id: 1201, pId: 123, name: "移动端餐厅定义", title: "", value: "CrmWeb/APP/CTDY/APP_CTDY_Srch.aspx" },
     { id: 1201, pId: 123, name: "移动端餐桌类型定义", title: "", value: "CrmWeb/APP/CZLXDY/APP_CZLXDY_Srch.aspx" },
     { id: 1201, pId: 123, name: "移动端餐桌定义", title: "", value: "CrmWeb/APP/CZDY/APP_CZDY_Srch.aspx" },
     { id: 1201, pId: 123, name: "移动端菜品类型定义", title: "", value: "CrmWeb/APP/CPLXDY/APP_CPLXDY_Srch.aspx" },
     { id: 1201, pId: 123, name: "移动端菜品定义", title: "", value: "CrmWeb/APP/CPDY/APP_CPDY_Srch.aspx" },
     { id: 1201, pId: 123, name: "移动端抽奖定义单", title: "", value: "CrmWeb/APP/CJDYD/APP_CJDYD_Srch.aspx?djlx=2" },
     { id: 1201, pId: 123, name: "移动端抢红包定义单", title: "", value: "CrmWeb/APP/CJDYD/APP_CJDYD_Srch.aspx?djlx=1" },
     { id: 1201, pId: 123, name: "移动端刮刮卡定义单", title: "", value: "CrmWeb/APP/CJDYD/APP_CJDYD_Srch.aspx?djlx=3" },
     { id: 1201, pId: 123, name: "移动端促销活动定义", title: "", value: "CrmWeb/APP/YDDCXHDDY/APP_YDDCXHDDY_Srch.aspx" },
     { id: 1201, pId: 123, name: "移动端礼品类型定义", title: "", value: "CrmWeb/APP/LPFLDY/APP_LPFLDY.aspx" },
     { id: 1201, pId: 123, name: "移动端礼品信息定义", title: "", value: "CrmWeb/APP/LPXXDY/APP_LPXXDY_Srch.aspx" },


      { id: 124, pId: 11, name: "短信平台", title: "1" },
      { id: 1102, pId: 124, name: "卡到期提醒", title: "ys", value: "CrmWeb/DXPT/KDQTX/DXPT_KDQTX.aspx" },
      { id: 1102, pId: 124, name: "会员消费排名", title: "ys", value: "CrmWeb/DXPT/HYXFPM/DXPT_HYXFPM.aspx" },
      { id: 1102, pId: 124, name: "按品牌消费排名", title: "ys", value: "CrmWeb/DXPT/PPXFPM/DXPT_PPXFPM.aspx" },
      { id: 1102, pId: 124, name: "可升级提醒", title: "ys", value: "CrmWeb/DXPT/KSJTX/DXPT_KSJTX.aspx" },
      { id: 1102, pId: 124, name: "即将升级提醒", title: "ys", value: "CrmWeb/DXPT/JJSJTX/DXPT_JJSJTX.aspx" },
      { id: 1102, pId: 124, name: "生日短信", title: "ys", value: "CrmWeb/DXPT/SRDX/DXPT_SRDX_Srch.aspx" },
      { id: 1102, pId: 124, name: "短信通道定义", title: "ys", value: "CrmWeb/DXPT/DXTDDY/DXPT_DXTDDY.aspx" },
      { id: 1102, pId: 124, name: "即将降级会员提醒", title: "ys", value: "CrmWeb/DXPT/JJJJHY/DXPT_JJJJHY.aspx" },
      { id: 1102, pId: 124, name: "已降级会员提醒", title: "ys", value: "CrmWeb/DXPT/YJJHY/DXPT_YJJHY.aspx" },
      { id: 1102, pId: 124, name: "快捷发送内容设置", title: "ys", value: "CrmWeb/DXPT/KJFSNRDEF/DXPT_KJFSNRDEF.aspx" },
      { id: 1102, pId: 124, name: "顾客价值分类消费排名", title: "ys", value: "CrmWeb/DXPT/HYGKJZXFPM/DXPT_HYGKJZXFPM.aspx" },
      { id: 1102, pId: 124, name: "个性化符号定义", title: "ys", value: "CrmWeb/DXPT/GXHFHDY/DXPT_GXHFHDY_Proc.aspx" },

      { id: 1102, pId: 124, name: "按分类消费排名", title: "ys", value: "CrmWeb/DXPT/FLXFPM/DXPT_FLXFPM.aspx" },
      { id: 1102, pId: 124, name: "会员短信发送设置", title: "ys", value: "CrmWeb/DXPT/SENDSMSDEF/DXPT_SENDSMSDEF.aspx" },
      { id: 1102, pId: 124, name: "会员按品牌消费排名", title: "ys", value: "CrmWeb/DXPT/SBPMTX/DXPT_SBPMTX.aspx" },
      { id: 1102, pId: 124, name: "会员按分类消费排名", title: "ys", value: "CrmWeb/DXPT/SPFLPMTX/DXPT_SPFLPMTX.aspx" },
      { id: 1102, pId: 124, name: "按门店品牌分类排名", title: "ys", value: "CrmWeb/DXPT/PPFLHYXFPM/DXPT_PPFLHYXFPM.aspx" },

      { id: 1102, pId: 124, name: "短信活动主题定义 ", title: "ys", value: "CrmWeb/DXPT/DXHDZTDY/DXPT_DXHDZTDY_Srch.aspx" },
      { id: 1102, pId: 124, name: "快捷发送内容设置 ", title: "ys", value: "CrmWeb/DXPT/KJFSNRDEF/DXPT_KJFSNRDEF.aspx" },



    { id: 130, pId: 11, name: "异业联盟", title: "1" },
   { id: 1301, pId: 130, name: "发放查询_商户1", title: "lbf", value: "../../CrmWeb/YYLMGL/YYLMHX/YYLMYHQSH_Search.aspx?id=1" },
   { id: 1302, pId: 130, name: "发放查询_商户2", title: "lbf", value: "../../CrmWeb/YYLMGL/YYLMHX/YYLMYHQSH_Search.aspx?id=2" },
   { id: 1302, pId: 130, name: "兑换码发放", title: "lbf", value: "../../CrmWeb/YYLMGL/DHMFF/YYLMYHQFF.aspx?action=add" },
   { id: 1302, pId: 130, name: "发放查询", title: "lbf", value: "../../CrmWeb/YYLMGL/YYLMHX/YYLMYHQSH_Srch.aspx?id=2" },
   { id: 1302, pId: 130, name: "兑换码核销", title: "lbf", value: "../../CrmWeb/YYLMGL/YYLMHX/YYLMYHQSH.aspx?action=add" },
];
