insert into BFSYSTEM (SYSID, SYSMC, SYS_VERSION, BASE_PKG_NAME, DBSERVER, DBNAME, WEBSERVER, TYPE, QXBJ, INITPAGE)
values (510, 'CRM系统', '800', 'CRMLIB', null, null, '/CRM/', 0, 1, null);

insert into BFPUB.SYSLIB (ID, LIBNAME, SYSID, DESCRIPT, PACKAGE_NAME, FLAG_INSTALL, FLAG_RCL, RCLZZSJ, RCLSX, FLAG_RCL_FD)
values (5160000, 'CRM系统管理', 510, 'CRMCZK', 'CRMCZK', 1, 0, null, null, null);

insert into BFPUB.SYSLIB (ID, LIBNAME, SYSID, DESCRIPT, PACKAGE_NAME, FLAG_INSTALL, FLAG_RCL, RCLZZSJ, RCLSX, FLAG_RCL_FD)
values (5161000, '会员卡管理', 510, 'CRMCZK', 'CRMCZK', 1, 0, null, null, null);

insert into BFPUB.SYSLIB (ID, LIBNAME, SYSID, DESCRIPT, PACKAGE_NAME, FLAG_INSTALL, FLAG_RCL, RCLZZSJ, RCLSX, FLAG_RCL_FD)
values (5164000, '客服平台', 510, 'CRMCZK', 'CRMCZK', 1, 0, null, null, null);

insert into BFPUB.SYSLIB (ID, LIBNAME, SYSID, DESCRIPT, PACKAGE_NAME, FLAG_INSTALL, FLAG_RCL, RCLZZSJ, RCLSX, FLAG_RCL_FD)
values (5164500, '监控平台', 510, 'CRMCZK', 'CRMCZK', 1, 0, null, null, null);

insert into BFPUB.SYSLIB (ID, LIBNAME, SYSID, DESCRIPT, PACKAGE_NAME, FLAG_INSTALL, FLAG_RCL, RCLZZSJ, RCLSX, FLAG_RCL_FD)
values (5165000, '面值卡管理', 510, 'CRMCZK', 'CRMCZK', 1, 0, null, null, null);

insert into BFPUB.SYSLIB (ID, LIBNAME, SYSID, DESCRIPT, PACKAGE_NAME, FLAG_INSTALL, FLAG_RCL, RCLZZSJ, RCLSX, FLAG_RCL_FD)
values (5166000, '会员消费', 510, 'CRMCZK', 'CRMCZK', 1, 0, null, null, null);

insert into BFPUB.SYSLIB (ID, LIBNAME, SYSID, DESCRIPT, PACKAGE_NAME, FLAG_INSTALL, FLAG_RCL, RCLZZSJ, RCLSX, FLAG_RCL_FD)
values (5167000, '会员卡优惠券', 510, 'CRMCZK', 'CRMCZK', 1, 0, null, null, null);

insert into BFPUB.SYSLIB (ID, LIBNAME, SYSID, DESCRIPT, PACKAGE_NAME, FLAG_INSTALL, FLAG_RCL, RCLZZSJ, RCLSX, FLAG_RCL_FD)
values (5167500, '微信沟通平台', 510, 'CRMCZK', 'CRMCZK', 1, 0, null, null, null);

insert into BFPUB.SYSLIB (ID, LIBNAME, SYSID, DESCRIPT, PACKAGE_NAME, FLAG_INSTALL, FLAG_RCL, RCLZZSJ, RCLSX, FLAG_RCL_FD)
values (5168000, '呼叫中心', 510, 'CRMCZK', 'CRMCZK', 1, 0, null, null, null);

insert into BFPUB.SYSLIB (ID, LIBNAME, SYSID, DESCRIPT, PACKAGE_NAME, FLAG_INSTALL, FLAG_RCL, RCLZZSJ, RCLSX, FLAG_RCL_FD)
values (5168500, '礼品管理', 510, 'CRMCZK', 'CRMCZK', 1, 0, null, null, null);

insert into BFPUB.SYSLIB (ID, LIBNAME, SYSID, DESCRIPT, PACKAGE_NAME, FLAG_INSTALL, FLAG_RCL, RCLZZSJ, RCLSX, FLAG_RCL_FD)
values (5169000, '分析报表', 510, 'CRMCZK', 'CRMCZK', 1, 0, null, null, null);

