insert into RCLPROC (GROUP_ID, STEP, PROCEDURE_NAME, PROCEDURE_PARAM, MS, STATUS)
values (5161000, 1, 'HYXF_QD_HYCXDJ', 'pRCLRQ,pZXR', '启动促销单据', 1);

insert into RCLPROC (GROUP_ID, STEP, PROCEDURE_NAME, PROCEDURE_PARAM, MS, STATUS)
values (5161000, 2, 'HYK_YHQ_QD_CXDJ', 'pRCLRQ,pZXR', '启动优惠券促销活动单据', 1);

insert into RCLPROC (GROUP_ID, STEP, PROCEDURE_NAME, PROCEDURE_PARAM, MS, STATUS)
values (5161000, 3, 'HYK_PROC_UPDATECRMJZRQ', 'pRCLRQ', '更新记账日期', 1);

insert into RCLPROC (GROUP_ID, STEP, PROCEDURE_NAME, PROCEDURE_PARAM, MS, STATUS)
values (5161000, 4, 'HYK_PROC_HYK_CZK_RBB', 'pRCLRQ', '储值卡日报表', 1);

insert into RCLPROC (GROUP_ID, STEP, PROCEDURE_NAME, PROCEDURE_PARAM, MS, STATUS)
values (5161000, 5, 'HYK_PROC_HYK_KCCZKBGZ', 'pRCLRQ,pNY', '库存卡保管帐', 1);

insert into RCLPROC (GROUP_ID, STEP, PROCEDURE_NAME, PROCEDURE_PARAM, MS, STATUS)
values (5161000, 6, 'HYK_PROC_MZK_XFRBB', 'pRCLRQ', '金额帐消费日报表', 1);

insert into RCLPROC (GROUP_ID, STEP, PROCEDURE_NAME, PROCEDURE_PARAM, MS, STATUS)
values (5161000, 7, 'HYK_PROC_HYK_YHQ_XFRBB', 'pRCLRQ', '优惠券帐消费日报表', 1);

insert into RCLPROC (GROUP_ID, STEP, PROCEDURE_NAME, PROCEDURE_PARAM, MS, STATUS)
values (5161000, 8, 'HYKGL_ZX_HYK_SMZTGZ', 'pRCLRQ', '会员卡转为睡眠状态', 1);

insert into RCLPROC (GROUP_ID, STEP, PROCEDURE_NAME, PROCEDURE_PARAM, MS, STATUS)
values (5161000, 9, 'HYKGL_ZX_HYK_JGDJGZ', 'pRCLRQ', '会员卡警告等级变动', 1);

insert into RCLPROC (GROUP_ID, STEP, PROCEDURE_NAME, PROCEDURE_PARAM, MS, STATUS)
values (5161000, 10, 'HYXF_ZX_HYK_YXQYCGZ', 'pRCLRQ', '会员卡有效期延长规则', 1);

insert into RCLPROC (GROUP_ID, STEP, PROCEDURE_NAME, PROCEDURE_PARAM, MS, STATUS)
values (5161000, 11, 'HYXF_ZX_HYK_ZTBG', 'pRCLRQ', '会员卡状态变动处理', 1);

insert into RCLPROC (GROUP_ID, STEP, PROCEDURE_NAME, PROCEDURE_PARAM, MS, STATUS)
values (5161000, 12, 'HYKGL_ZX_HYK_YXQDQDJ', 'pRCLRQ', '有效期到期冻结', 1);

insert into RCLPROC (GROUP_ID, STEP, PROCEDURE_NAME, PROCEDURE_PARAM, MS, STATUS)
values (5166000, 13, 'HYK_PROC_HYK_JFFLGZ', 'pRCLRQ', '积分处理', 1);

insert into RCLPROC (GROUP_ID, STEP, PROCEDURE_NAME, PROCEDURE_PARAM, MS, STATUS)
values (5166000, 14, 'HYK_PROC_HYK_YHQ_RBB', 'pRCLRQ', '优惠券帐日报表', 1);

insert into RCLPROC (GROUP_ID, STEP, PROCEDURE_NAME, PROCEDURE_PARAM, MS, STATUS)
values (5166000, 15, 'HYK_PROC_HYK_JFFHLPJXC', 'pRCLRQ', '积分返还礼品进销存报表', 1);

insert into RCLPROC (GROUP_ID, STEP, PROCEDURE_NAME, PROCEDURE_PARAM, MS, STATUS)
values (5166000, 16, 'HYK_PROC_CZK_XFHZ', 'pRCLRQ', '汇总储值卡消费明细', 1);

insert into RCLPROC (GROUP_ID, STEP, PROCEDURE_NAME, PROCEDURE_PARAM, MS, STATUS)
values (5166000, 17, 'HYK_MOVE_HYXF_BSK', 'pRCLRQ', '移动后台不刷卡历史记录到消费记录', 1);

insert into RCLPROC (GROUP_ID, STEP, PROCEDURE_NAME, PROCEDURE_PARAM, MS, STATUS)
values (5166000, 18, 'WRITE_HYK_XFMX', 'pRCLRQ', '汇总会员卡消费明细', 1);

insert into RCLPROC (GROUP_ID, STEP, PROCEDURE_NAME, PROCEDURE_PARAM, MS, STATUS)
values (5166000, 19, 'HYK_PROC_HYK_JFRBB', 'pRCLRQ', '会员卡积分日报表', 1);

insert into RCLPROC (GROUP_ID, STEP, PROCEDURE_NAME, PROCEDURE_PARAM, MS, STATUS)
values (5166000, 20, 'HYXF_ZX_HYK_DJSQGZ', 'pRCLRQ', '会员卡等级升迁', 1);

insert into RCLPROC (GROUP_ID, STEP, PROCEDURE_NAME, PROCEDURE_PARAM, MS, STATUS)
values (5166000, 21, 'WRITE_HYK_GZXFJFR', 'pRCLRQ', '汇总柜组消费积分', 1);

insert into RCLPROC (GROUP_ID, STEP, PROCEDURE_NAME, PROCEDURE_PARAM, MS, STATUS)
values (5167000, 22, 'HYK_PROC_SP_CXHZ', 'pRCLRQ', '按商品汇总促销优惠券金额', 1);

insert into RCLPROC (GROUP_ID, STEP, PROCEDURE_NAME, PROCEDURE_PARAM, MS, STATUS)
values (5167000, 23, 'HZ_YHQ_CXHDBYBM', 'pRCLRQ', '按部门汇总促销优惠券金额', 1);

insert into RCLPROC (GROUP_ID, STEP, PROCEDURE_NAME, PROCEDURE_PARAM, MS, STATUS)
values (5167000, 24, 'HZ_YHQ_CXHDBYHT', 'pRCLRQ', '按合同汇总促销优惠券金额', 1);

insert into RCLPROC (GROUP_ID, STEP, PROCEDURE_NAME, PROCEDURE_PARAM, MS, STATUS)
values (5167000, 25, 'HZ_MBJZ_CXHDSJ', 'pRCLRQ', '汇总满百减折数据', 1);

insert into RCLPROC (GROUP_ID, STEP, PROCEDURE_NAME, PROCEDURE_PARAM, MS, STATUS)
values (5169000, 26, 'HYK_PROC_MOVE_XFJL', 'pRCLRQ', '将消费数据移动到会员消费纪录中', 1);

insert into RCLPROC (GROUP_ID, STEP, PROCEDURE_NAME, PROCEDURE_PARAM, MS, STATUS)
values (5169000, 27, 'HYK_PROC_DEL_XFJL', 'pRCLRQ', '将消费数据删除', 1);
